apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubewatcher-agent.fullname" . }}
  labels:
    {{- include "kubewatcher-agent.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kubewatcher-agent.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "kubewatcher-agent.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
