apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "argus-runner.serviceAccountName" . }}
  labels:
    {{- include "argus-runner.labels" . | nindent 4 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "argus-runner.fullname" . }}-secret
  labels:
    {{- include "argus-runner.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-key: {{ .Values.env.RUNNER_API_KEY | quote }}
