{{- if .Values.grafana.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubewatcher-monitoring.fullname" . }}-grafana-datasources
  labels:
    {{- include "kubewatcher-monitoring.labels" . | nindent 4 }}
data:
  prometheus.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: {{ .Values.grafana.prometheusURL | default "http://kubewatcher-prometheus:9090" | quote }}
        access: proxy
        isDefault: true
{{- end }}
