{{- if .Values.ollama.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubewatcher-monitoring.fullname" . }}-ollama
  labels:
    {{- include "kubewatcher-monitoring.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ollama.service.type | default "ClusterIP" }}
  ports:
    - port: 11434
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "kubewatcher-monitoring.name" . }}-ollama
{{- end }}
