package context

import (
	"fmt"
	"strings"
	"time"

	"github.com/argues/argus/internal/alerts"
)

// GenerateDiagnosis produces a root cause hypothesis, confidence score, cascade
// notes, and ready-to-paste kubectl runbook steps from an assembled context bundle.
//
// This is the local pattern-matching engine. For Pro tier with Vertex AI, the
// hypothesis would be generated by the LLM with this bundle as context.
func GenerateDiagnosis(bundle *Bundle) *alerts.Diagnosis {
	if bundle == nil {
		return nil
	}

	alert := bundle.Alert
	diag := &alerts.Diagnosis{
		AlertID: alert.ID,
	}

	// Route to the correct pattern matcher.
	switch {
	case isOOMAlert(alert):
		diagnoseOOM(bundle, diag)
	case isCrashLoopAlert(alert):
		diagnoseCrashLoop(bundle, diag)
	case isDiskPressureAlert(alert):
		diagnoseDiskPressure(bundle, diag)
	case isCPUThrottleAlert(alert):
		diagnoseCPUThrottle(bundle, diag)
	case isImagePullAlert(alert):
		diagnoseImagePull(bundle, diag)
	case isMemoryPressureAlert(alert):
		diagnoseMemoryPressure(bundle, diag)
	default:
		diagnoseGeneric(bundle, diag)
	}

	// Enrich with cascade context.
	if len(bundle.CascadeAlerts) > 0 {
		diag.CascadeNote = buildCascadeNote(alert, bundle.CascadeAlerts)
	}

	// Enrich with decision log context.
	if len(bundle.DecisionLog) > 0 {
		var parts []string
		for _, entry := range bundle.DecisionLog {
			parts = append(parts, fmt.Sprintf("[%s] %s", entry.Date, strings.TrimSpace(entry.Content)))
		}
		diag.DecisionLogEntry = strings.Join(parts, "\n")
	}

	// Enrich with anomaly detection results.
	if len(bundle.AnomalyResults) > 0 {
		for _, ar := range bundle.AnomalyResults {
			if ar.IsAnomaly {
				diag.Hypothesis += fmt.Sprintf(
					" Anomstack detected anomaly on %s (score: %.2f, model: %s).",
					ar.MetricName, ar.Score, ar.ModelUsed,
				)
				diag.Confidence = clamp(diag.Confidence+0.1, 0, 1)
			}
		}
	}

	return diag
}

// --- Pattern matchers ---

func diagnoseOOM(b *Bundle, d *alerts.Diagnosis) {
	a := b.Alert
	d.Confidence = 0.85

	// Check if this correlates with a recent deploy.
	if a.DeployTime.IsZero() {
		d.Hypothesis = fmt.Sprintf(
			"Container %s exceeded memory limit (%s). %d restarts indicate a memory leak or undersized limit.",
			deployBase(a.PodName), a.MemoryLimit, a.RestartCount,
		)
	} else {
		d.Hypothesis = fmt.Sprintf(
			"Deploy at %s introduced %s. Container exceeded memory limit (%s) with %d restarts. "+
				"Likely cause: new code path or config change increasing heap usage. Rollback recommended.",
			a.DeployTime.Format("15:04 UTC"), a.ImageTag, a.MemoryLimit, a.RestartCount,
		)
		d.Confidence = 0.92
	}

	d.Steps = []alerts.RunbookStep{
		{Number: 1, Text: "Rollback deployment to previous stable version",
			Command: fmt.Sprintf("kubectl rollout undo deploy/%s -n %s", deployBase(a.PodName), a.Namespace)},
		{Number: 2, Text: "Confirm pods stabilise and restarts stop",
			Command: fmt.Sprintf("kubectl rollout status deploy/%s -n %s", deployBase(a.PodName), a.Namespace)},
		{Number: 3, Text: "Capture heap dump before full termination for analysis",
			Command: fmt.Sprintf("kubectl exec -it %s -n %s -- jcmd 1 GC.heap_dump /tmp/heap.hprof", a.PodName, a.Namespace)},
		{Number: 4, Text: fmt.Sprintf("Increase memory limit to %s in staging before next deploy", suggestMemoryBump(a.MemoryLimit))},
	}
}

func diagnoseCrashLoop(b *Bundle, d *alerts.Diagnosis) {
	a := b.Alert
	d.Confidence = 0.78
	d.Hypothesis = fmt.Sprintf(
		"Container %s is in CrashLoopBackOff with %d restarts. Check application logs for the root cause — "+
			"common causes include missing config/secrets, failed health checks, or startup errors.",
		deployBase(a.PodName), a.RestartCount,
	)

	d.Steps = []alerts.RunbookStep{
		{Number: 1, Text: "Check container logs for the crash reason",
			Command: fmt.Sprintf("kubectl logs %s -n %s --previous", a.PodName, a.Namespace)},
		{Number: 2, Text: "Describe pod for events and conditions",
			Command: fmt.Sprintf("kubectl describe pod %s -n %s", a.PodName, a.Namespace)},
		{Number: 3, Text: "Check if configmaps/secrets are mounted correctly",
			Command: fmt.Sprintf("kubectl get pod %s -n %s -o jsonpath='{.spec.containers[0].env}'", a.PodName, a.Namespace)},
		{Number: 4, Text: "If config is correct, rollback the deployment",
			Command: fmt.Sprintf("kubectl rollout undo deploy/%s -n %s", deployBase(a.PodName), a.Namespace)},
	}
}

func diagnoseDiskPressure(b *Bundle, d *alerts.Diagnosis) {
	a := b.Alert
	d.Confidence = 0.88

	// Check for cascading impact.
	var evictedMonitoring []string
	for _, ea := range a.EvictedPods {
		if isMonitoringComponent(ea) {
			evictedMonitoring = append(evictedMonitoring, ea)
		}
	}

	d.Hypothesis = fmt.Sprintf(
		"DiskPressure on %s (%.0f%% used). Pods are being evicted.",
		a.NodeName, a.DiskUsage*100,
	)

	if len(evictedMonitoring) > 0 {
		d.Hypothesis += fmt.Sprintf(
			" Monitoring components evicted (%s) — this may break HPA autoscaling and alerting for other workloads.",
			strings.Join(evictedMonitoring, ", "),
		)
		d.Confidence = 0.94
	}

	d.Steps = []alerts.RunbookStep{
		{Number: 1, Text: "Cordon node to prevent new scheduling",
			Command: fmt.Sprintf("kubectl cordon %s", a.NodeName)},
		{Number: 2, Text: "Identify and clean large files (e.g. Prometheus WAL)",
			Command: fmt.Sprintf("kubectl debug node/%s -it --image=busybox -- du -sh /host/var/lib/*", a.NodeName)},
		{Number: 3, Text: "Expand PVC or reduce retention if Prometheus is the culprit",
			Command: "kubectl patch pvc prometheus-data -n monitoring -p '{\"spec\":{\"resources\":{\"requests\":{\"storage\":\"50Gi\"}}}}'"},
		{Number: 4, Text: "Uncordon node after disk usage drops below 70%",
			Command: fmt.Sprintf("kubectl uncordon %s", a.NodeName)},
	}
}

func diagnoseCPUThrottle(b *Bundle, d *alerts.Diagnosis) {
	a := b.Alert
	d.Confidence = 0.75

	// Check cascade: is HPA broken due to metrics-server eviction?
	hpaBroken := false
	for _, ca := range b.CascadeAlerts {
		if isDiskPressureAlert(ca) {
			for _, ep := range ca.EvictedPods {
				if strings.Contains(strings.ToLower(ep), "metrics-server") ||
					strings.Contains(strings.ToLower(ep), "prometheus") {
					hpaBroken = true
					break
				}
			}
		}
	}

	if hpaBroken {
		d.Hypothesis = fmt.Sprintf(
			"HPA is not triggering scale-out for %s despite %.0f%% CPU throttling. "+
				"Likely cause: metrics-server or prometheus-adapter was evicted (see DiskPressure alert). "+
				"Fix node pressure first — HPA will recover once metrics are available.",
			deployBase(a.PodName), a.CPUThrottle,
		)
		d.Confidence = 0.93

		d.Steps = []alerts.RunbookStep{
			{Number: 1, Text: "Resolve DiskPressure on the affected node first (metrics-server evicted)"},
			{Number: 2, Text: "Verify HPA can see CPU metrics",
				Command: fmt.Sprintf("kubectl describe hpa %s -n %s", deployBase(a.PodName), a.Namespace)},
			{Number: 3, Text: "Temporarily bump replicas while HPA recovers",
				Command: fmt.Sprintf("kubectl scale deploy/%s --replicas=5 -n %s", deployBase(a.PodName), a.Namespace)},
			{Number: 4, Text: fmt.Sprintf("Raise CPU limit to %s in staging review", suggestCPUBump(a.CPULimit))},
		}
	} else {
		d.Hypothesis = fmt.Sprintf(
			"CPU throttling at %.0f%% on %s. Requests are queuing. Consider horizontal scale-out or raising CPU limits.",
			a.CPUThrottle, deployBase(a.PodName),
		)

		d.Steps = []alerts.RunbookStep{
			{Number: 1, Text: "Check HPA status and current replica count",
				Command: fmt.Sprintf("kubectl describe hpa %s -n %s", deployBase(a.PodName), a.Namespace)},
			{Number: 2, Text: "Scale out manually if HPA is not responding",
				Command: fmt.Sprintf("kubectl scale deploy/%s --replicas=5 -n %s", deployBase(a.PodName), a.Namespace)},
			{Number: 3, Text: "Review CPU limits for the deployment",
				Command: fmt.Sprintf("kubectl get deploy %s -n %s -o jsonpath='{.spec.template.spec.containers[0].resources}'", deployBase(a.PodName), a.Namespace)},
			{Number: 4, Text: fmt.Sprintf("Raise CPU limit to %s in staging", suggestCPUBump(a.CPULimit))},
		}
	}
}

func diagnoseImagePull(b *Bundle, d *alerts.Diagnosis) {
	a := b.Alert
	d.Confidence = 0.90
	d.Hypothesis = fmt.Sprintf(
		"Unable to pull image %s. Common causes: wrong tag, private registry without imagePullSecret, "+
			"or registry outage.",
		a.ImageTag,
	)

	d.Steps = []alerts.RunbookStep{
		{Number: 1, Text: "Check pod events for detailed pull error",
			Command: fmt.Sprintf("kubectl describe pod %s -n %s | grep -A5 Events", a.PodName, a.Namespace)},
		{Number: 2, Text: "Verify the image exists in the registry",
			Command: fmt.Sprintf("docker manifest inspect %s", a.ImageTag)},
		{Number: 3, Text: "Check imagePullSecrets are configured",
			Command: fmt.Sprintf("kubectl get pod %s -n %s -o jsonpath='{.spec.imagePullSecrets}'", a.PodName, a.Namespace)},
		{Number: 4, Text: "If local dev, load image into Minikube",
			Command: fmt.Sprintf("minikube image load %s", a.ImageTag)},
	}
}

func diagnoseMemoryPressure(b *Bundle, d *alerts.Diagnosis) {
	a := b.Alert
	d.Confidence = 0.80
	d.Hypothesis = fmt.Sprintf(
		"MemoryPressure on node %s. Pods may be evicted to reclaim memory. "+
			"Check for memory-hungry workloads or missing resource limits.",
		a.NodeName,
	)

	d.Steps = []alerts.RunbookStep{
		{Number: 1, Text: "List pods on the node sorted by memory usage",
			Command: fmt.Sprintf("kubectl top pods --sort-by=memory --field-selector spec.nodeName=%s", a.NodeName)},
		{Number: 2, Text: "Check which pods lack memory limits",
			Command: "kubectl get pods --all-namespaces -o json | jq '.items[] | select(.spec.containers[].resources.limits.memory == null) | .metadata.name'"},
		{Number: 3, Text: "Cordon the node if evictions are imminent",
			Command: fmt.Sprintf("kubectl cordon %s", a.NodeName)},
		{Number: 4, Text: "Drain non-critical workloads",
			Command: fmt.Sprintf("kubectl drain %s --ignore-daemonsets --delete-emptydir-data", a.NodeName)},
	}
}

func diagnoseGeneric(b *Bundle, d *alerts.Diagnosis) {
	a := b.Alert
	d.Confidence = 0.50
	d.Hypothesis = fmt.Sprintf(
		"Alert detected on %s in namespace %s. Review pod status and events for more context.",
		a.PodName, a.Namespace,
	)

	d.Steps = []alerts.RunbookStep{
		{Number: 1, Text: "Describe the pod for events and conditions",
			Command: fmt.Sprintf("kubectl describe pod %s -n %s", a.PodName, a.Namespace)},
		{Number: 2, Text: "Check container logs",
			Command: fmt.Sprintf("kubectl logs %s -n %s --tail=100", a.PodName, a.Namespace)},
		{Number: 3, Text: "Check resource usage",
			Command: fmt.Sprintf("kubectl top pod %s -n %s", a.PodName, a.Namespace)},
	}
}

// --- Cascade reasoning ---

func buildCascadeNote(target alerts.Alert, cascade []alerts.Alert) string {
	if len(cascade) == 0 {
		return ""
	}

	var parts []string
	for _, ca := range cascade {
		relation := ca.Name
		if ca.Timestamp.Before(target.Timestamp) {
			relation += " (preceded this alert)"
		} else {
			relation += " (followed this alert)"
		}
		parts = append(parts, relation)
	}

	note := fmt.Sprintf(
		"Cascade detected — %d correlated alert(s): %s. ",
		len(cascade),
		strings.Join(parts, "; "),
	)

	// Add actionable advice.
	if len(cascade) > 0 {
		// Find the earliest alert in the cascade — likely the root cause.
		earliest := cascade[0]
		for _, ca := range cascade[1:] {
			if ca.Timestamp.Before(earliest.Timestamp) {
				earliest = ca
			}
		}
		if earliest.Timestamp.Before(target.Timestamp) {
			note += fmt.Sprintf("Root cause candidate: %s (fired %s before this alert). Investigate that first.",
				earliest.Name, target.Timestamp.Sub(earliest.Timestamp).Truncate(time.Second))
		}
	}

	return note
}

// --- Alert type detection ---

func isOOMAlert(a alerts.Alert) bool {
	return strings.Contains(strings.ToLower(a.Name), "oom")
}

func isCrashLoopAlert(a alerts.Alert) bool {
	return strings.Contains(strings.ToLower(a.Name), "crashloop")
}

func isDiskPressureAlert(a alerts.Alert) bool {
	lower := strings.ToLower(a.Name)
	return strings.Contains(lower, "disk") && strings.Contains(lower, "pressure")
}

func isCPUThrottleAlert(a alerts.Alert) bool {
	lower := strings.ToLower(a.Name)
	return strings.Contains(lower, "cpu") && (strings.Contains(lower, "throttl") || strings.Contains(lower, "throttle"))
}

func isImagePullAlert(a alerts.Alert) bool {
	return strings.Contains(strings.ToLower(a.Name), "imagepull")
}

func isMemoryPressureAlert(a alerts.Alert) bool {
	lower := strings.ToLower(a.Name)
	return strings.Contains(lower, "memory") && strings.Contains(lower, "pressure")
}

// --- Helpers ---

func deployBase(podName string) string {
	parts := strings.Split(podName, "-")
	if len(parts) >= 3 {
		return strings.Join(parts[:len(parts)-2], "-")
	}
	if len(parts) >= 2 {
		return parts[0]
	}
	return podName
}

func suggestMemoryBump(current string) string {
	// Simple heuristic: suggest 1.5x.
	switch current {
	case "256Mi":
		return "384Mi"
	case "512Mi":
		return "768Mi"
	case "1Gi":
		return "1.5Gi"
	case "2Gi":
		return "3Gi"
	default:
		return "increase by 50%"
	}
}

func suggestCPUBump(current string) string {
	switch current {
	case "250m":
		return "500m"
	case "500m":
		return "1000m"
	case "1000m", "1":
		return "2000m"
	default:
		return "double current limit"
	}
}

func clamp(val, min, max float64) float64 {
	if val < min {
		return min
	}
	if val > max {
		return max
	}
	return val
}
