// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {alertproc} from '../models';
import {context} from '../models';
import {k8s} from '../models';
import {http} from '../models';
import {setup} from '../models';
import {oauthproviders} from '../models';
import {pkg} from '../models';
import {agentconn} from '../models';
import {workspace} from '../models';
import {incidents} from '../models';
import {runbooks} from '../models';
import {alerts} from '../models';
import {saasapi} from '../models';
import {ai} from '../models';
import {anomaly} from '../models';
import {argocd} from '../models';
import {loadtest} from '../models';
import {features} from '../models';
import {config} from '../models';
import {workflows} from '../models';
import {broker} from '../models';
import {notebooks} from '../models';
import {terminal} from '../models';
import {vulnscan} from '../models';
import {popeye} from '../models';
import {envprobe} from '../models';
import {auth} from '../models';

export function AcceptSuggestion(arg1:string,arg2:string):Promise<void>;

export function AckAlert(arg1:string,arg2:string):Promise<void>;

export function AlertInvestigations(arg1:string,arg2:number):Promise<Array<alertproc.Investigation>>;

export function AnalyzeDB(arg1:context.Context,arg2:string,arg3:string):Promise<Record<string, any>>;

export function AnalyzeEndpointReadiness(arg1:string,arg2:string):Promise<k8s.EndpointReadiness>;

export function AnalyzeLabelMatch(arg1:string,arg2:string):Promise<k8s.LabelDiffResult>;

export function AppendGoogleDoc(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function ApplyYaml(arg1:string):Promise<string>;

export function AuthRoutes(arg1:http.ServeMux):Promise<void>;

export function AuthenticateWithBiometrics(arg1:string):Promise<void>;

export function AutoResolveContext():Promise<k8s.ContextResolution>;

export function BatchCheckCanI(arg1:string,arg2:Array<k8s.CanIResult>):Promise<Array<k8s.CanIResult>>;

export function CancelDistributedLoadTest(arg1:string):Promise<void>;

export function CancelOAuthFlow(arg1:string):Promise<boolean>;

export function CheckAuthStatus():Promise<k8s.AuthCheckResult>;

export function CheckCanI(arg1:string,arg2:string,arg3:string,arg4:string):Promise<k8s.CanIResult>;

export function CheckToolStatus():Promise<Array<setup.ToolStatus>>;

export function CheckTopologyAwareRouting(arg1:string):Promise<Array<k8s.TopologyWarning>>;

export function ClearSessionToken():Promise<void>;

export function ClearUsageHistory():Promise<void>;

export function ClearUserActivity():Promise<void>;

export function CloseExecSession():Promise<void>;

export function CloseTerminalSession(arg1:string):Promise<void>;

export function CompleteOAuthFlow(arg1:string,arg2:string):Promise<oauthproviders.UserInfo>;

export function CompleteWorkspaceConnect(arg1:string,arg2:string,arg3:string):Promise<pkg.WorkspaceConnectionView>;

export function ConnectToAgent(arg1:string):Promise<Array<agentconn.Anomaly>>;

export function CorrelatePodEvents(arg1:string,arg2:string,arg3:number):Promise<k8s.CorrelationResult>;

export function CreateCodeReviewReport(arg1:string,arg2:string,arg3:string,arg4:string):Promise<pkg.CodeReviewReport>;

export function CreateExternalBridge(arg1:k8s.ExternalBridgeSpec):Promise<k8s.BridgeResult>;

export function CreateGoogleDoc(arg1:string,arg2:string,arg3:string,arg4:string):Promise<workspace.Doc>;

export function CreateGoogleSheet(arg1:string,arg2:string,arg3:string):Promise<workspace.Sheet>;

export function CreateGoogleTask(arg1:string,arg2:string,arg3:string,arg4:workspace.Task):Promise<workspace.Task>;

export function CreateIncident(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<incidents.Incident>;

export function CreateNotebookFolder(arg1:string):Promise<void>;

export function CreateRunbook(arg1:string,arg2:string):Promise<runbooks.Runbook>;

export function CurrentMetrics():Promise<alerts.ClusterMetrics>;

export function DeleteAnomalyRule(arg1:string):Promise<void>;

export function DeleteCodeReviewReport(arg1:string,arg2:string):Promise<void>;

export function DeleteDBConnection(arg1:context.Context,arg2:string):Promise<void>;

export function DeleteGoogleTask(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function DeleteIncident(arg1:string):Promise<void>;

export function DeleteNotebook(arg1:string):Promise<void>;

export function DeletePod(arg1:string,arg2:string):Promise<void>;

export function DeleteResource(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteRunbook(arg1:string):Promise<void>;

export function DeleteVaultSecret(arg1:string):Promise<void>;

export function DeleteWorkflow(arg1:string):Promise<void>;

export function DeleteWorkspaceConnection(arg1:string,arg2:string):Promise<void>;

export function DeployAgent(arg1:string):Promise<setup.SetupResult>;

export function DescribeSecretRef(arg1:string):Promise<pkg.SecretRefInfo>;

export function DiagnoseAlert(arg1:string):Promise<context.Bundle>;

export function DismissSuggestion(arg1:string,arg2:string):Promise<void>;

export function DuplicateWorkload(arg1:string,arg2:string,arg3:string):Promise<k8s.DuplicateResult>;

export function EmitLogLine(arg1:alerts.LogLine):Promise<void>;

export function EstimateCosts(arg1:string):Promise<k8s.ClusterCostReport>;

export function EstimateDistLoadCost(arg1:saasapi.DistLoadSpec):Promise<number>;

export function ExecPodShell(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number):Promise<void>;

export function ExplainTerminalOutput(arg1:string,arg2:string):Promise<string>;

export function FindOrphanedEndpoints(arg1:string):Promise<Array<k8s.OrphanedEndpoint>>;

export function GenerateCommand(arg1:string,arg2:string):Promise<string>;

export function GenerateLoadTestPayload(arg1:string,arg2:number):Promise<string>;

export function GenerateTrafficSplitHTTPRoute(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Array<k8s.BackendRefWeight>):Promise<string>;

export function GenerateWorkloadYAML(arg1:k8s.WorkloadSpec):Promise<k8s.WorkloadYAML>;

export function GetAgentEventLog():Promise<Array<ai.AgentEvent>>;

export function GetAgentProfile():Promise<alertproc.AgentProfile>;

export function GetAgentTopology(arg1:string):Promise<agentconn.TopologyGraph>;

export function GetAlerts():Promise<Array<alerts.Alert>>;

export function GetAnomalyJobs():Promise<Array<anomaly.Job>>;

export function GetAnomalyRules():Promise<Array<anomaly.Rule>>;

export function GetAnomalySettings():Promise<anomaly.Settings>;

export function GetAppMode():Promise<string>;

export function GetArgusCDApp(arg1:string):Promise<argocd.App>;

export function GetArgusCDDiffs(arg1:string):Promise<Array<argocd.AppDiff>>;

export function GetArgusCDResources(arg1:string):Promise<Array<argocd.AppResource>>;

export function GetArgusCDStatus():Promise<pkg.ArgusCDStatus>;

export function GetAutoSummary(arg1:string):Promise<ai.AutoSummary>;

export function GetBlastRadiusInfo():Promise<k8s.BlastRadiusInfo>;

export function GetChatHistory(arg1:string):Promise<Array<ai.ChatEntry>>;

export function GetClusterInfo():Promise<k8s.ClusterInfo>;

export function GetCodeReviewReport(arg1:string,arg2:string):Promise<string>;

export function GetCodeSuggestion(arg1:string,arg2:string):Promise<string>;

export function GetCommonPermissions(arg1:string):Promise<Array<k8s.CanIResult>>;

export function GetCrashLogs(arg1:string,arg2:string,arg3:string):Promise<k8s.CrashInfo>;

export function GetDBConnection(arg1:context.Context,arg2:string):Promise<pkg.DBConnectionView>;

export function GetDeployArtifact(arg1:string,arg2:string):Promise<pkg.DeployArtifact>;

export function GetDeployArtifacts():Promise<Array<pkg.DeployArtifact>>;

export function GetDeploymentRevisions(arg1:string,arg2:string,arg3:number):Promise<Array<k8s.DeploymentRevision>>;

export function GetDistLoadCreditBalance():Promise<number>;

export function GetDistLoadCreditHistory():Promise<Array<saasapi.CreditTransaction>>;

export function GetDistLoadHistory():Promise<Array<saasapi.DistLoadStatus>>;

export function GetDistLoadUsage():Promise<saasapi.LoadUsageSummary>;

export function GetDistributedLoadTestRecord(arg1:string):Promise<loadtest.RunRecord>;

export function GetDistributedLoadTestResult(arg1:string):Promise<saasapi.DistLoadStatus>;

export function GetDistributedLoadTestStatus(arg1:string):Promise<saasapi.DistLoadStatus>;

export function GetFeatures():Promise<Record<features.Feature, boolean>>;

export function GetGatewayStatusByRole(arg1:string):Promise<any>;

export function GetGoogleSheet(arg1:string,arg2:string,arg3:string):Promise<workspace.Sheet>;

export function GetLocalDistLoadQuota():Promise<pkg.LocalQuotaStatus>;

export function GetMetrics():Promise<alerts.ClusterMetrics>;

export function GetNextSuggestion(arg1:string):Promise<pkg.NextSuggestionResult>;

export function GetNodeCapacities():Promise<Array<k8s.NodeCapacity>>;

export function GetNodeLogs(arg1:string,arg2:number):Promise<Array<k8s.NodeLogEntry>>;

export function GetNotebook(arg1:string):Promise<string>;

export function GetPRGuidelines(arg1:string):Promise<string>;

export function GetPodLogs(arg1:string,arg2:string,arg3:number):Promise<Array<alerts.LogLine>>;

export function GetResourceDetail(arg1:string,arg2:string,arg3:string):Promise<k8s.ResourceDetailResult>;

export function GetResourceSuggestion(arg1:string):Promise<k8s.ResourceSuggestion>;

export function GetResourceYaml(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetRouteTopologyGraph(arg1:string):Promise<k8s.GatewayRouteGraph>;

export function GetRunbook(arg1:string):Promise<string>;

export function GetRunnerStreamURL(arg1:string):Promise<string>;

export function GetSecretStoreInfo():Promise<pkg.SecretStoreInfo>;

export function GetServicePods(arg1:string,arg2:string):Promise<Array<k8s.ServicePod>>;

export function GetSessionToken():Promise<string>;

export function GetSettings():Promise<pkg.SettingsPayload>;

export function GetTShirtSizes():Promise<Record<string, k8s.ResourceProfile>>;

export function GetTier():Promise<config.Tier>;

export function GetTopology(arg1:string):Promise<k8s.TopologyResult>;

export function GetUsageSummary():Promise<pkg.UsagePayload>;

export function GetVPARecommendations(arg1:string):Promise<Array<k8s.VPARecommendation>>;

export function GetVaultStatus():Promise<Array<pkg.VaultEntry>>;

export function GetWorkflow(arg1:string):Promise<workflows.Workflow>;

export function GetZoneDistribution(arg1:string,arg2:string):Promise<k8s.ZoneDistribution>;

export function HandleURL(arg1:string):Promise<void>;

export function HandleWebhook(arg1:http.ResponseWriter,arg2:http.Request):Promise<void>;

export function ImpersonateUser(arg1:string,arg2:Array<string>):Promise<k8s.ImpersonationView>;

export function InjectDebugContainer(arg1:string,arg2:string,arg3:string):Promise<k8s.DebugSession>;

export function InstallArgusScan():Promise<setup.SetupResult>;

export function IsBiometricAvailable():Promise<boolean>;

export function LaunchPopOutTerminal():Promise<void>;

export function ListAllNamespaces():Promise<Array<string>>;

export function ListApplications(arg1:string):Promise<Array<k8s.Application>>;

export function ListArgusCDApps(arg1:string):Promise<Array<argocd.App>>;

export function ListArgusCDProjects():Promise<Array<string>>;

export function ListCodeReviewReports(arg1:string):Promise<Array<pkg.CodeReviewReport>>;

export function ListContexts():Promise<Array<k8s.ContextInfo>>;

export function ListDBConnections(arg1:context.Context):Promise<Array<pkg.DBConnectionView>>;

export function ListDistLoadBrokerKinds():Promise<Array<broker.Kind>>;

export function ListDistLoadPresets():Promise<Array<loadtest.Preset>>;

export function ListDistLoadRegions():Promise<Array<saasapi.RegionOption>>;

export function ListEncryptedSecretSources(arg1:string):Promise<Array<pkg.SecretSource>>;

export function ListEndpointSlices(arg1:string):Promise<Array<k8s.EndpointSliceInfo>>;

export function ListExternalBridges(arg1:string):Promise<Array<k8s.ExternalBridge>>;

export function ListGatewayClasses():Promise<Array<k8s.GatewaySummary>>;

export function ListGateways(arg1:string):Promise<Array<k8s.GatewaySummary>>;

export function ListGitHubBranches():Promise<Array<pkg.GitHubBranch>>;

export function ListGitHubPullRequests():Promise<Array<pkg.GitHubPullRequest>>;

export function ListGoogleChatSpaces(arg1:string,arg2:string):Promise<Array<pkg.GChatSpaceView>>;

export function ListGoogleTaskLists(arg1:string,arg2:string):Promise<Array<workspace.TaskList>>;

export function ListGoogleTasks(arg1:string,arg2:string,arg3:string):Promise<Array<workspace.Task>>;

export function ListHTTPRoutes(arg1:string):Promise<Array<k8s.HTTPRouteSummary>>;

export function ListIncidents():Promise<Array<incidents.Incident>>;

export function ListNamespaces():Promise<Array<string>>;

export function ListNotebooks():Promise<Array<notebooks.FileEntry>>;

export function ListOAuthProviders():Promise<Array<oauthproviders.ProviderInfo>>;

export function ListRegistryTags(arg1:string):Promise<Array<k8s.RegistryTag>>;

export function ListResources(arg1:string,arg2:string):Promise<k8s.ResourceListResult>;

export function ListRunbooks():Promise<Array<runbooks.Runbook>>;

export function ListServiceSelectors(arg1:string):Promise<Array<k8s.ServiceSelectorInfo>>;

export function ListSlackChannels(arg1:string,arg2:string):Promise<Array<pkg.SlackChannelView>>;

export function ListSpotChecks():Promise<Array<string>>;

export function ListTerminalSessions():Promise<Array<terminal.SessionInfo>>;

export function ListVaultSecrets():Promise<Array<pkg.VaultSecret>>;

export function ListVulnerabilities():Promise<Array<vulnscan.ScannedImage>>;

export function ListWorkflows():Promise<Array<workflows.WorkflowSummary>>;

export function ListWorkspaceConnections(arg1:string):Promise<Array<pkg.WorkspaceConnectionView>>;

export function ListWorkspaceServices():Promise<Array<string>>;

export function LoginSaaS(arg1:string):Promise<string>;

export function MarkAlertIgnored(arg1:string):Promise<void>;

export function MoveNotebook(arg1:string,arg2:string):Promise<void>;

export function MuteSuggestion(arg1:string):Promise<void>;

export function PingExternalEndpoint(arg1:string,arg2:string):Promise<boolean>;

export function PollOAuthFlow(arg1:string):Promise<pkg.OAuthPollResult>;

export function ProfileWaste(arg1:string):Promise<k8s.WasteProfile>;

export function QueryLogs(arg1:string,arg2:string,arg3:number):Promise<k8s.LogQueryResult>;

export function QueryPromQL(arg1:context.Context,arg2:string,arg3:string):Promise<Array<number>>;

export function QueryTimeSeriesMetrics(arg1:string,arg2:string):Promise<Array<number>>;

export function ReadGoogleDoc(arg1:string,arg2:string,arg3:string):Promise<workspace.DocBody>;

export function ReadGoogleSheetRange(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<any>>;

export function RecordView(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RefreshArgusCDApp(arg1:string,arg2:boolean):Promise<void>;

export function ResizeExec(arg1:number,arg2:number):Promise<void>;

export function ResizeTerminal(arg1:number,arg2:number):Promise<void>;

export function ResizeTerminalSession(arg1:string,arg2:number,arg3:number):Promise<void>;

export function ResolveLocalPayloadPath(arg1:string):Promise<pkg.PayloadPathResolution>;

export function ResolveSecretRef(arg1:string):Promise<string|string>;

export function RestartDeployment(arg1:string,arg2:string):Promise<void>;

export function RollbackArgusCDApp(arg1:string,arg2:number):Promise<void>;

export function RunArgusScan():Promise<popeye.Report>;

export function RunCodeSandbox(arg1:string,arg2:string):Promise<string>;

export function RunCronJob(arg1:string,arg2:string):Promise<string>;

export function RunEnvProbes():Promise<Array<envprobe.Result>>;

export function RunSpotCheck(arg1:string):Promise<void>;

export function RunSpotChecks():Promise<void>;

export function SaveAnomalyRule(arg1:anomaly.Rule):Promise<void>;

export function SaveAnomalySettings(arg1:anomaly.Settings):Promise<void>;

export function SaveNotebook(arg1:string,arg2:string):Promise<void>;

export function SavePRGuidelines(arg1:string,arg2:string):Promise<void>;

export function SaveRunbook(arg1:string,arg2:string):Promise<void>;

export function SaveWorkflow(arg1:workflows.Workflow):Promise<workflows.Workflow>;

export function ScaleDeployment(arg1:string,arg2:string,arg3:number):Promise<void>;

export function ScanAllImages(arg1:string):Promise<Array<vulnscan.ScannedImage>>;

export function ScanImage(arg1:string,arg2:string):Promise<string>;

export function SendChatMessage(arg1:string,arg2:string):Promise<string>;

export function SendExecInput(arg1:string):Promise<void>;

export function SendGoogleChatMessage(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SendSlackMessage(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SendTerminalInput(arg1:string):Promise<void>;

export function SendTerminalSessionInput(arg1:string,arg2:string):Promise<void>;

export function ServeHTTP(arg1:http.ResponseWriter,arg2:http.Request):Promise<void>;

export function SetAgentProfile(arg1:alertproc.AgentProfile):Promise<void>;

export function SetPaused(arg1:boolean):Promise<void>;

export function SetSessionToken(arg1:string):Promise<void>;

export function SetVaultSecret(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetupAuth(arg1:auth.Store,arg2:config.AuthConfig):Promise<void>;

export function SilenceAlert(arg1:string,arg2:number,arg3:string):Promise<void>;

export function StartDistributedLoadTest(arg1:saasapi.DistLoadSpec):Promise<string>;

export function StartEnvProbeLoop(arg1:context.Context):Promise<void>;

export function StartEventLoop(arg1:context.Context):Promise<void>;

export function StartHTTPServer(arg1:number):Promise<void>;

export function StartOAuthFlow(arg1:string):Promise<string>;

export function StartRunnerLoadTest(arg1:saasapi.DistLoadSpec):Promise<string>;

export function StartTerminal(arg1:number,arg2:number):Promise<void>;

export function StartTerminalSession(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number):Promise<void>;

export function StartWorkspaceConnect(arg1:string,arg2:string,arg3:string):Promise<workspace.AuthURL>;

export function StreamPodLogsFollow(arg1:string,arg2:string,arg3:string,arg4:number):Promise<Array<string>>;

export function SwitchContext(arg1:string):Promise<void>;

export function SyncApplication(arg1:string,arg2:string):Promise<void>;

export function SyncArgusCDApp(arg1:string,arg2:string):Promise<argocd.SyncResult>;

export function TestArgusCDConnection():Promise<void>;

export function TestDBConnection(arg1:context.Context,arg2:string):Promise<pkg.DBConnectionTestResult>;

export function TestS3Connection():Promise<void>;

export function TestSecretsTool(arg1:string):Promise<pkg.SecretsToolStatus>;

export function TestVaultProvider(arg1:string):Promise<pkg.VaultEntry>;

export function ToggleAnomalyRule(arg1:string):Promise<boolean>;

export function TranslateIngressToGateway(arg1:string):Promise<k8s.MigrationResult>;

export function UndeployAgent(arg1:string):Promise<setup.SetupResult>;

export function UpdateBillingRates(arg1:number,arg2:number,arg3:number):Promise<void>;

export function UpdateGoogleTask(arg1:string,arg2:string,arg3:string,arg4:string,arg5:workspace.Task):Promise<workspace.Task>;

export function UpdateIncident(arg1:string,arg2:string,arg3:string):Promise<incidents.Incident>;

export function UpdateSettings(arg1:pkg.SettingsPayload):Promise<void>;

export function UpsertDBConnection(arg1:context.Context,arg2:pkg.DBConnectionInput):Promise<pkg.DBConnectionView>;

export function ValidateEnvFile(arg1:string,arg2:string,arg3:string):Promise<pkg.EnvValidationResult>;

export function WorkspaceRoutes(arg1:http.ServeMux):Promise<void>;

export function WriteGoogleSheetRange(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Array<any>):Promise<void>;
