// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {alertproc} from '../models';
import {http} from '../models';
import {setup} from '../models';
import {context} from '../models';
import {oauthproviders} from '../models';
import {agentconn} from '../models';
import {pkg} from '../models';
import {incidents} from '../models';
import {runbooks} from '../models';
import {alerts} from '../models';
import {k8s} from '../models';
import {ai} from '../models';
import {anomaly} from '../models';
import {argocd} from '../models';
import {features} from '../models';
import {config} from '../models';
import {workflows} from '../models';
import {notebooks} from '../models';
import {vulnscan} from '../models';
import {popeye} from '../models';
import {auth} from '../models';

export function AckAlert(arg1:string,arg2:string):Promise<void>;

export function AlertInvestigations(arg1:string,arg2:number):Promise<Array<alertproc.Investigation>>;

export function ApplyYaml(arg1:string):Promise<string>;

export function AuthRoutes(arg1:http.ServeMux):Promise<void>;

export function CancelOAuthFlow(arg1:string):Promise<boolean>;

export function CheckToolStatus():Promise<Array<setup.ToolStatus>>;

export function ClearUsageHistory():Promise<void>;

export function CloseExecSession():Promise<void>;

export function CompleteOAuthFlow(arg1:context.Context,arg2:string,arg3:string):Promise<oauthproviders.UserInfo>;

export function ConnectToAgent(arg1:string):Promise<Array<agentconn.Anomaly>>;

export function CreateCodeReviewReport(arg1:string,arg2:string,arg3:string,arg4:string):Promise<pkg.CodeReviewReport>;

export function CreateIncident(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<incidents.Incident>;

export function CreateNotebookFolder(arg1:string):Promise<void>;

export function CreateRunbook(arg1:string,arg2:string):Promise<runbooks.Runbook>;

export function CurrentMetrics():Promise<alerts.ClusterMetrics>;

export function DeleteAnomalyRule(arg1:string):Promise<void>;

export function DeleteCodeReviewReport(arg1:string,arg2:string):Promise<void>;

export function DeleteIncident(arg1:string):Promise<void>;

export function DeleteNotebook(arg1:string):Promise<void>;

export function DeletePod(arg1:string,arg2:string):Promise<void>;

export function DeleteResource(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteRunbook(arg1:string):Promise<void>;

export function DeleteVaultSecret(arg1:string):Promise<void>;

export function DeleteWorkflow(arg1:string):Promise<void>;

export function DeployAgent(arg1:string):Promise<setup.SetupResult>;

export function DescribeSecretRef(arg1:string):Promise<pkg.SecretRefInfo>;

export function DiagnoseAlert(arg1:string):Promise<context.Bundle>;

export function EmitLogLine(arg1:alerts.LogLine):Promise<void>;

export function EstimateCosts(arg1:string):Promise<k8s.ClusterCostReport>;

export function ExecPodShell(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number):Promise<void>;

export function GetAgentEventLog():Promise<Array<ai.AgentEvent>>;

export function GetAgentProfile():Promise<alertproc.AgentProfile>;

export function GetAgentTopology(arg1:string):Promise<agentconn.TopologyGraph>;

export function GetAlerts():Promise<Array<alerts.Alert>>;

export function GetAnomalyJobs():Promise<Array<anomaly.Job>>;

export function GetAnomalyRules():Promise<Array<anomaly.Rule>>;

export function GetAnomalySettings():Promise<anomaly.Settings>;

export function GetAppMode():Promise<string>;

export function GetArgusCDApp(arg1:string):Promise<argocd.App>;

export function GetArgusCDDiffs(arg1:string):Promise<Array<argocd.AppDiff>>;

export function GetArgusCDResources(arg1:string):Promise<Array<argocd.AppResource>>;

export function GetArgusCDStatus():Promise<pkg.ArgusCDStatus>;

export function GetAutoSummary(arg1:string):Promise<ai.AutoSummary>;

export function GetChatHistory(arg1:string):Promise<Array<ai.ChatEntry>>;

export function GetClusterInfo():Promise<k8s.ClusterInfo>;

export function GetCodeReviewReport(arg1:string,arg2:string):Promise<string>;

export function GetCodeSuggestion(arg1:string,arg2:string):Promise<string>;

export function GetDeployArtifact(arg1:string,arg2:string):Promise<pkg.DeployArtifact>;

export function GetDeployArtifacts():Promise<Array<pkg.DeployArtifact>>;

export function GetDeploymentRevisions(arg1:string,arg2:string,arg3:number):Promise<Array<k8s.DeploymentRevision>>;

export function GetFeatures():Promise<Record<features.Feature, boolean>>;

export function GetMetrics():Promise<alerts.ClusterMetrics>;

export function GetNodeLogs(arg1:string,arg2:number):Promise<Array<k8s.NodeLogEntry>>;

export function GetNotebook(arg1:string):Promise<string>;

export function GetPRGuidelines(arg1:string):Promise<string>;

export function GetPodLogs(arg1:string,arg2:string,arg3:number):Promise<Array<alerts.LogLine>>;

export function GetResourceDetail(arg1:string,arg2:string,arg3:string):Promise<k8s.ResourceDetailResult>;

export function GetResourceYaml(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetRunbook(arg1:string):Promise<string>;

export function GetServicePods(arg1:string,arg2:string):Promise<Array<k8s.ServicePod>>;

export function GetSettings():Promise<pkg.SettingsPayload>;

export function GetTier():Promise<config.Tier>;

export function GetTopology(arg1:string):Promise<k8s.TopologyResult>;

export function GetUsageSummary():Promise<pkg.UsagePayload>;

export function GetVPARecommendations(arg1:string):Promise<Array<k8s.VPARecommendation>>;

export function GetVaultStatus():Promise<Array<pkg.VaultEntry>>;

export function GetWorkflow(arg1:string):Promise<workflows.Workflow>;

export function HandleURL(arg1:string):Promise<void>;

export function HandleWebhook(arg1:http.ResponseWriter,arg2:http.Request):Promise<void>;

export function InstallArgusScan():Promise<setup.SetupResult>;

export function LaunchPopOutTerminal():Promise<void>;

export function ListAllNamespaces():Promise<Array<string>>;

export function ListApplications(arg1:string):Promise<Array<k8s.Application>>;

export function ListArgusCDApps(arg1:string):Promise<Array<argocd.App>>;

export function ListArgusCDProjects():Promise<Array<string>>;

export function ListCodeReviewReports(arg1:string):Promise<Array<pkg.CodeReviewReport>>;

export function ListContexts():Promise<Array<k8s.ContextInfo>>;

export function ListEncryptedSecretSources(arg1:string):Promise<Array<pkg.SecretSource>>;

export function ListGitHubBranches():Promise<Array<pkg.GitHubBranch>>;

export function ListGitHubPullRequests():Promise<Array<pkg.GitHubPullRequest>>;

export function ListIncidents():Promise<Array<incidents.Incident>>;

export function ListNotebooks():Promise<Array<notebooks.FileEntry>>;

export function ListOAuthProviders():Promise<Array<oauthproviders.ProviderInfo>>;

export function ListResources(arg1:string,arg2:string):Promise<k8s.ResourceListResult>;

export function ListRunbooks():Promise<Array<runbooks.Runbook>>;

export function ListSpotChecks():Promise<Array<string>>;

export function ListVaultSecrets():Promise<Array<pkg.VaultSecret>>;

export function ListVulnerabilities():Promise<Array<vulnscan.ScannedImage>>;

export function ListWorkflows():Promise<Array<workflows.WorkflowSummary>>;

export function LoginSaaS(arg1:string):Promise<string>;

export function MarkAlertIgnored(arg1:string):Promise<void>;

export function MoveNotebook(arg1:string,arg2:string):Promise<void>;

export function PollOAuthFlow(arg1:string):Promise<pkg.OAuthPollResult>;

export function QueryLogs(arg1:string,arg2:string,arg3:number):Promise<k8s.LogQueryResult>;

export function QueryTimeSeriesMetrics(arg1:string,arg2:string):Promise<Array<number>>;

export function RefreshArgusCDApp(arg1:string,arg2:boolean):Promise<void>;

export function ResizeExec(arg1:number,arg2:number):Promise<void>;

export function ResizeTerminal(arg1:number,arg2:number):Promise<void>;

export function ResolveSecretRef(arg1:string):Promise<string|string>;

export function RestartDeployment(arg1:string,arg2:string):Promise<void>;

export function RollbackArgusCDApp(arg1:string,arg2:number):Promise<void>;

export function RunArgusScan():Promise<popeye.Report>;

export function RunCodeSandbox(arg1:string,arg2:string):Promise<string>;

export function RunSpotCheck(arg1:string):Promise<void>;

export function RunSpotChecks():Promise<void>;

export function SaveAnomalyRule(arg1:anomaly.Rule):Promise<void>;

export function SaveAnomalySettings(arg1:anomaly.Settings):Promise<void>;

export function SaveNotebook(arg1:string,arg2:string):Promise<void>;

export function SavePRGuidelines(arg1:string,arg2:string):Promise<void>;

export function SaveRunbook(arg1:string,arg2:string):Promise<void>;

export function SaveWorkflow(arg1:workflows.Workflow):Promise<workflows.Workflow>;

export function ScaleDeployment(arg1:string,arg2:string,arg3:number):Promise<void>;

export function ScanAllImages(arg1:string):Promise<Array<vulnscan.ScannedImage>>;

export function ScanImage(arg1:string,arg2:string):Promise<string>;

export function SendChatMessage(arg1:string,arg2:string):Promise<string>;

export function SendExecInput(arg1:string):Promise<void>;

export function SendTerminalInput(arg1:string):Promise<void>;

export function ServeHTTP(arg1:http.ResponseWriter,arg2:http.Request):Promise<void>;

export function SetAgentProfile(arg1:alertproc.AgentProfile):Promise<void>;

export function SetPaused(arg1:boolean):Promise<void>;

export function SetVaultSecret(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetupAuth(arg1:auth.Store,arg2:config.AuthConfig):Promise<void>;

export function SilenceAlert(arg1:string,arg2:number,arg3:string):Promise<void>;

export function StartEventLoop(arg1:context.Context):Promise<void>;

export function StartHTTPServer(arg1:number):Promise<void>;

export function StartOAuthFlow(arg1:string):Promise<string>;

export function StartTerminal(arg1:number,arg2:number):Promise<void>;

export function StreamPodLogsFollow(arg1:string,arg2:string,arg3:string,arg4:number):Promise<Array<string>>;

export function SwitchContext(arg1:string):Promise<void>;

export function SyncApplication(arg1:string,arg2:string):Promise<void>;

export function SyncArgusCDApp(arg1:string,arg2:string):Promise<argocd.SyncResult>;

export function TestArgusCDConnection():Promise<void>;

export function TestS3Connection():Promise<void>;

export function TestSecretsTool(arg1:string):Promise<pkg.SecretsToolStatus>;

export function TestVaultProvider(arg1:string):Promise<pkg.VaultEntry>;

export function ToggleAnomalyRule(arg1:string):Promise<boolean>;

export function UndeployAgent(arg1:string):Promise<setup.SetupResult>;

export function UpdateBillingRates(arg1:number,arg2:number,arg3:number):Promise<void>;

export function UpdateIncident(arg1:string,arg2:string,arg3:string):Promise<incidents.Incident>;

export function UpdateSettings(arg1:pkg.SettingsPayload):Promise<void>;

export function ValidateEnvFile(arg1:string,arg2:string,arg3:string):Promise<pkg.EnvValidationResult>;
