// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AckAlert(arg1, arg2) {
  return window['go']['pkg']['App']['AckAlert'](arg1, arg2);
}

export function AlertInvestigations(arg1, arg2) {
  return window['go']['pkg']['App']['AlertInvestigations'](arg1, arg2);
}

export function ApplyYaml(arg1) {
  return window['go']['pkg']['App']['ApplyYaml'](arg1);
}

export function AuthRoutes(arg1) {
  return window['go']['pkg']['App']['AuthRoutes'](arg1);
}

export function CancelOAuthFlow(arg1) {
  return window['go']['pkg']['App']['CancelOAuthFlow'](arg1);
}

export function CheckToolStatus() {
  return window['go']['pkg']['App']['CheckToolStatus']();
}

export function ClearUsageHistory() {
  return window['go']['pkg']['App']['ClearUsageHistory']();
}

export function CloseExecSession() {
  return window['go']['pkg']['App']['CloseExecSession']();
}

export function CompleteOAuthFlow(arg1, arg2, arg3) {
  return window['go']['pkg']['App']['CompleteOAuthFlow'](arg1, arg2, arg3);
}

export function ConnectToAgent(arg1) {
  return window['go']['pkg']['App']['ConnectToAgent'](arg1);
}

export function CreateCodeReviewReport(arg1, arg2, arg3, arg4) {
  return window['go']['pkg']['App']['CreateCodeReviewReport'](arg1, arg2, arg3, arg4);
}

export function CreateIncident(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['pkg']['App']['CreateIncident'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateNotebookFolder(arg1) {
  return window['go']['pkg']['App']['CreateNotebookFolder'](arg1);
}

export function CreateRunbook(arg1, arg2) {
  return window['go']['pkg']['App']['CreateRunbook'](arg1, arg2);
}

export function CurrentMetrics() {
  return window['go']['pkg']['App']['CurrentMetrics']();
}

export function DeleteAnomalyRule(arg1) {
  return window['go']['pkg']['App']['DeleteAnomalyRule'](arg1);
}

export function DeleteCodeReviewReport(arg1, arg2) {
  return window['go']['pkg']['App']['DeleteCodeReviewReport'](arg1, arg2);
}

export function DeleteIncident(arg1) {
  return window['go']['pkg']['App']['DeleteIncident'](arg1);
}

export function DeleteNotebook(arg1) {
  return window['go']['pkg']['App']['DeleteNotebook'](arg1);
}

export function DeletePod(arg1, arg2) {
  return window['go']['pkg']['App']['DeletePod'](arg1, arg2);
}

export function DeleteResource(arg1, arg2, arg3) {
  return window['go']['pkg']['App']['DeleteResource'](arg1, arg2, arg3);
}

export function DeleteRunbook(arg1) {
  return window['go']['pkg']['App']['DeleteRunbook'](arg1);
}

export function DeleteVaultSecret(arg1) {
  return window['go']['pkg']['App']['DeleteVaultSecret'](arg1);
}

export function DeleteWorkflow(arg1) {
  return window['go']['pkg']['App']['DeleteWorkflow'](arg1);
}

export function DeployAgent(arg1) {
  return window['go']['pkg']['App']['DeployAgent'](arg1);
}

export function DescribeSecretRef(arg1) {
  return window['go']['pkg']['App']['DescribeSecretRef'](arg1);
}

export function DiagnoseAlert(arg1) {
  return window['go']['pkg']['App']['DiagnoseAlert'](arg1);
}

export function EmitLogLine(arg1) {
  return window['go']['pkg']['App']['EmitLogLine'](arg1);
}

export function EstimateCosts(arg1) {
  return window['go']['pkg']['App']['EstimateCosts'](arg1);
}

export function ExecPodShell(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['pkg']['App']['ExecPodShell'](arg1, arg2, arg3, arg4, arg5);
}

export function GetAgentEventLog() {
  return window['go']['pkg']['App']['GetAgentEventLog']();
}

export function GetAgentProfile() {
  return window['go']['pkg']['App']['GetAgentProfile']();
}

export function GetAgentTopology(arg1) {
  return window['go']['pkg']['App']['GetAgentTopology'](arg1);
}

export function GetAlerts() {
  return window['go']['pkg']['App']['GetAlerts']();
}

export function GetAnomalyJobs() {
  return window['go']['pkg']['App']['GetAnomalyJobs']();
}

export function GetAnomalyRules() {
  return window['go']['pkg']['App']['GetAnomalyRules']();
}

export function GetAnomalySettings() {
  return window['go']['pkg']['App']['GetAnomalySettings']();
}

export function GetAppMode() {
  return window['go']['pkg']['App']['GetAppMode']();
}

export function GetArgusCDApp(arg1) {
  return window['go']['pkg']['App']['GetArgusCDApp'](arg1);
}

export function GetArgusCDDiffs(arg1) {
  return window['go']['pkg']['App']['GetArgusCDDiffs'](arg1);
}

export function GetArgusCDResources(arg1) {
  return window['go']['pkg']['App']['GetArgusCDResources'](arg1);
}

export function GetArgusCDStatus() {
  return window['go']['pkg']['App']['GetArgusCDStatus']();
}

export function GetAutoSummary(arg1) {
  return window['go']['pkg']['App']['GetAutoSummary'](arg1);
}

export function GetChatHistory(arg1) {
  return window['go']['pkg']['App']['GetChatHistory'](arg1);
}

export function GetClusterInfo() {
  return window['go']['pkg']['App']['GetClusterInfo']();
}

export function GetCodeReviewReport(arg1, arg2) {
  return window['go']['pkg']['App']['GetCodeReviewReport'](arg1, arg2);
}

export function GetCodeSuggestion(arg1, arg2) {
  return window['go']['pkg']['App']['GetCodeSuggestion'](arg1, arg2);
}

export function GetDeployArtifact(arg1, arg2) {
  return window['go']['pkg']['App']['GetDeployArtifact'](arg1, arg2);
}

export function GetDeployArtifacts() {
  return window['go']['pkg']['App']['GetDeployArtifacts']();
}

export function GetDeploymentRevisions(arg1, arg2, arg3) {
  return window['go']['pkg']['App']['GetDeploymentRevisions'](arg1, arg2, arg3);
}

export function GetFeatures() {
  return window['go']['pkg']['App']['GetFeatures']();
}

export function GetMetrics() {
  return window['go']['pkg']['App']['GetMetrics']();
}

export function GetNodeLogs(arg1, arg2) {
  return window['go']['pkg']['App']['GetNodeLogs'](arg1, arg2);
}

export function GetNotebook(arg1) {
  return window['go']['pkg']['App']['GetNotebook'](arg1);
}

export function GetPRGuidelines(arg1) {
  return window['go']['pkg']['App']['GetPRGuidelines'](arg1);
}

export function GetPodLogs(arg1, arg2, arg3) {
  return window['go']['pkg']['App']['GetPodLogs'](arg1, arg2, arg3);
}

export function GetResourceDetail(arg1, arg2, arg3) {
  return window['go']['pkg']['App']['GetResourceDetail'](arg1, arg2, arg3);
}

export function GetResourceYaml(arg1, arg2, arg3) {
  return window['go']['pkg']['App']['GetResourceYaml'](arg1, arg2, arg3);
}

export function GetRunbook(arg1) {
  return window['go']['pkg']['App']['GetRunbook'](arg1);
}

export function GetServicePods(arg1, arg2) {
  return window['go']['pkg']['App']['GetServicePods'](arg1, arg2);
}

export function GetSettings() {
  return window['go']['pkg']['App']['GetSettings']();
}

export function GetTier() {
  return window['go']['pkg']['App']['GetTier']();
}

export function GetTopology(arg1) {
  return window['go']['pkg']['App']['GetTopology'](arg1);
}

export function GetUsageSummary() {
  return window['go']['pkg']['App']['GetUsageSummary']();
}

export function GetVPARecommendations(arg1) {
  return window['go']['pkg']['App']['GetVPARecommendations'](arg1);
}

export function GetVaultStatus() {
  return window['go']['pkg']['App']['GetVaultStatus']();
}

export function GetWorkflow(arg1) {
  return window['go']['pkg']['App']['GetWorkflow'](arg1);
}

export function HandleURL(arg1) {
  return window['go']['pkg']['App']['HandleURL'](arg1);
}

export function HandleWebhook(arg1, arg2) {
  return window['go']['pkg']['App']['HandleWebhook'](arg1, arg2);
}

export function InstallArgusScan() {
  return window['go']['pkg']['App']['InstallArgusScan']();
}

export function LaunchPopOutTerminal() {
  return window['go']['pkg']['App']['LaunchPopOutTerminal']();
}

export function ListAllNamespaces() {
  return window['go']['pkg']['App']['ListAllNamespaces']();
}

export function ListApplications(arg1) {
  return window['go']['pkg']['App']['ListApplications'](arg1);
}

export function ListArgusCDApps(arg1) {
  return window['go']['pkg']['App']['ListArgusCDApps'](arg1);
}

export function ListArgusCDProjects() {
  return window['go']['pkg']['App']['ListArgusCDProjects']();
}

export function ListCodeReviewReports(arg1) {
  return window['go']['pkg']['App']['ListCodeReviewReports'](arg1);
}

export function ListContexts() {
  return window['go']['pkg']['App']['ListContexts']();
}

export function ListEncryptedSecretSources(arg1) {
  return window['go']['pkg']['App']['ListEncryptedSecretSources'](arg1);
}

export function ListGitHubBranches() {
  return window['go']['pkg']['App']['ListGitHubBranches']();
}

export function ListGitHubPullRequests() {
  return window['go']['pkg']['App']['ListGitHubPullRequests']();
}

export function ListIncidents() {
  return window['go']['pkg']['App']['ListIncidents']();
}

export function ListNotebooks() {
  return window['go']['pkg']['App']['ListNotebooks']();
}

export function ListOAuthProviders() {
  return window['go']['pkg']['App']['ListOAuthProviders']();
}

export function ListResources(arg1, arg2) {
  return window['go']['pkg']['App']['ListResources'](arg1, arg2);
}

export function ListRunbooks() {
  return window['go']['pkg']['App']['ListRunbooks']();
}

export function ListSpotChecks() {
  return window['go']['pkg']['App']['ListSpotChecks']();
}

export function ListVaultSecrets() {
  return window['go']['pkg']['App']['ListVaultSecrets']();
}

export function ListVulnerabilities() {
  return window['go']['pkg']['App']['ListVulnerabilities']();
}

export function ListWorkflows() {
  return window['go']['pkg']['App']['ListWorkflows']();
}

export function LoginSaaS(arg1) {
  return window['go']['pkg']['App']['LoginSaaS'](arg1);
}

export function MarkAlertIgnored(arg1) {
  return window['go']['pkg']['App']['MarkAlertIgnored'](arg1);
}

export function MoveNotebook(arg1, arg2) {
  return window['go']['pkg']['App']['MoveNotebook'](arg1, arg2);
}

export function PollOAuthFlow(arg1) {
  return window['go']['pkg']['App']['PollOAuthFlow'](arg1);
}

export function QueryLogs(arg1, arg2, arg3) {
  return window['go']['pkg']['App']['QueryLogs'](arg1, arg2, arg3);
}

export function QueryTimeSeriesMetrics(arg1, arg2) {
  return window['go']['pkg']['App']['QueryTimeSeriesMetrics'](arg1, arg2);
}

export function RefreshArgusCDApp(arg1, arg2) {
  return window['go']['pkg']['App']['RefreshArgusCDApp'](arg1, arg2);
}

export function ResizeExec(arg1, arg2) {
  return window['go']['pkg']['App']['ResizeExec'](arg1, arg2);
}

export function ResizeTerminal(arg1, arg2) {
  return window['go']['pkg']['App']['ResizeTerminal'](arg1, arg2);
}

export function ResolveSecretRef(arg1) {
  return window['go']['pkg']['App']['ResolveSecretRef'](arg1);
}

export function RestartDeployment(arg1, arg2) {
  return window['go']['pkg']['App']['RestartDeployment'](arg1, arg2);
}

export function RollbackArgusCDApp(arg1, arg2) {
  return window['go']['pkg']['App']['RollbackArgusCDApp'](arg1, arg2);
}

export function RunArgusScan() {
  return window['go']['pkg']['App']['RunArgusScan']();
}

export function RunCodeSandbox(arg1, arg2) {
  return window['go']['pkg']['App']['RunCodeSandbox'](arg1, arg2);
}

export function RunSpotCheck(arg1) {
  return window['go']['pkg']['App']['RunSpotCheck'](arg1);
}

export function RunSpotChecks() {
  return window['go']['pkg']['App']['RunSpotChecks']();
}

export function SaveAnomalyRule(arg1) {
  return window['go']['pkg']['App']['SaveAnomalyRule'](arg1);
}

export function SaveAnomalySettings(arg1) {
  return window['go']['pkg']['App']['SaveAnomalySettings'](arg1);
}

export function SaveNotebook(arg1, arg2) {
  return window['go']['pkg']['App']['SaveNotebook'](arg1, arg2);
}

export function SavePRGuidelines(arg1, arg2) {
  return window['go']['pkg']['App']['SavePRGuidelines'](arg1, arg2);
}

export function SaveRunbook(arg1, arg2) {
  return window['go']['pkg']['App']['SaveRunbook'](arg1, arg2);
}

export function SaveWorkflow(arg1) {
  return window['go']['pkg']['App']['SaveWorkflow'](arg1);
}

export function ScaleDeployment(arg1, arg2, arg3) {
  return window['go']['pkg']['App']['ScaleDeployment'](arg1, arg2, arg3);
}

export function ScanAllImages(arg1) {
  return window['go']['pkg']['App']['ScanAllImages'](arg1);
}

export function ScanImage(arg1, arg2) {
  return window['go']['pkg']['App']['ScanImage'](arg1, arg2);
}

export function SendChatMessage(arg1, arg2) {
  return window['go']['pkg']['App']['SendChatMessage'](arg1, arg2);
}

export function SendExecInput(arg1) {
  return window['go']['pkg']['App']['SendExecInput'](arg1);
}

export function SendTerminalInput(arg1) {
  return window['go']['pkg']['App']['SendTerminalInput'](arg1);
}

export function ServeHTTP(arg1, arg2) {
  return window['go']['pkg']['App']['ServeHTTP'](arg1, arg2);
}

export function SetAgentProfile(arg1) {
  return window['go']['pkg']['App']['SetAgentProfile'](arg1);
}

export function SetPaused(arg1) {
  return window['go']['pkg']['App']['SetPaused'](arg1);
}

export function SetVaultSecret(arg1, arg2, arg3) {
  return window['go']['pkg']['App']['SetVaultSecret'](arg1, arg2, arg3);
}

export function SetupAuth(arg1, arg2) {
  return window['go']['pkg']['App']['SetupAuth'](arg1, arg2);
}

export function SilenceAlert(arg1, arg2, arg3) {
  return window['go']['pkg']['App']['SilenceAlert'](arg1, arg2, arg3);
}

export function StartEventLoop(arg1) {
  return window['go']['pkg']['App']['StartEventLoop'](arg1);
}

export function StartHTTPServer(arg1) {
  return window['go']['pkg']['App']['StartHTTPServer'](arg1);
}

export function StartOAuthFlow(arg1) {
  return window['go']['pkg']['App']['StartOAuthFlow'](arg1);
}

export function StartTerminal(arg1, arg2) {
  return window['go']['pkg']['App']['StartTerminal'](arg1, arg2);
}

export function StreamPodLogsFollow(arg1, arg2, arg3, arg4) {
  return window['go']['pkg']['App']['StreamPodLogsFollow'](arg1, arg2, arg3, arg4);
}

export function SwitchContext(arg1) {
  return window['go']['pkg']['App']['SwitchContext'](arg1);
}

export function SyncApplication(arg1, arg2) {
  return window['go']['pkg']['App']['SyncApplication'](arg1, arg2);
}

export function SyncArgusCDApp(arg1, arg2) {
  return window['go']['pkg']['App']['SyncArgusCDApp'](arg1, arg2);
}

export function TestArgusCDConnection() {
  return window['go']['pkg']['App']['TestArgusCDConnection']();
}

export function TestS3Connection() {
  return window['go']['pkg']['App']['TestS3Connection']();
}

export function TestSecretsTool(arg1) {
  return window['go']['pkg']['App']['TestSecretsTool'](arg1);
}

export function TestVaultProvider(arg1) {
  return window['go']['pkg']['App']['TestVaultProvider'](arg1);
}

export function ToggleAnomalyRule(arg1) {
  return window['go']['pkg']['App']['ToggleAnomalyRule'](arg1);
}

export function UndeployAgent(arg1) {
  return window['go']['pkg']['App']['UndeployAgent'](arg1);
}

export function UpdateBillingRates(arg1, arg2, arg3) {
  return window['go']['pkg']['App']['UpdateBillingRates'](arg1, arg2, arg3);
}

export function UpdateIncident(arg1, arg2, arg3) {
  return window['go']['pkg']['App']['UpdateIncident'](arg1, arg2, arg3);
}

export function UpdateSettings(arg1) {
  return window['go']['pkg']['App']['UpdateSettings'](arg1);
}

export function ValidateEnvFile(arg1, arg2, arg3) {
  return window['go']['pkg']['App']['ValidateEnvFile'](arg1, arg2, arg3);
}
