// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptSuggestion(arg1, arg2) {
  return window['go']['pkg']['App']['AcceptSuggestion'](arg1, arg2);
}

export function AckAlert(arg1, arg2) {
  return window['go']['pkg']['App']['AckAlert'](arg1, arg2);
}

export function AlertInvestigations(arg1, arg2) {
  return window['go']['pkg']['App']['AlertInvestigations'](arg1, arg2);
}

export function AnalyzeEndpointReadiness(arg1, arg2) {
  return window['go']['pkg']['App']['AnalyzeEndpointReadiness'](arg1, arg2);
}

export function AnalyzeLabelMatch(arg1, arg2) {
  return window['go']['pkg']['App']['AnalyzeLabelMatch'](arg1, arg2);
}

export function ApplyYaml(arg1) {
  return window['go']['pkg']['App']['ApplyYaml'](arg1);
}

export function AuthRoutes(arg1) {
  return window['go']['pkg']['App']['AuthRoutes'](arg1);
}

export function AutoResolveContext() {
  return window['go']['pkg']['App']['AutoResolveContext']();
}

export function BatchCheckCanI(arg1, arg2) {
  return window['go']['pkg']['App']['BatchCheckCanI'](arg1, arg2);
}

export function CancelLoadTest(arg1) {
  return window['go']['pkg']['App']['CancelLoadTest'](arg1);
}

export function CancelOAuthFlow(arg1) {
  return window['go']['pkg']['App']['CancelOAuthFlow'](arg1);
}

export function CheckAuthStatus() {
  return window['go']['pkg']['App']['CheckAuthStatus']();
}

export function CheckCanI(arg1, arg2, arg3, arg4) {
  return window['go']['pkg']['App']['CheckCanI'](arg1, arg2, arg3, arg4);
}

export function CheckToolStatus() {
  return window['go']['pkg']['App']['CheckToolStatus']();
}

export function CheckTopologyAwareRouting(arg1) {
  return window['go']['pkg']['App']['CheckTopologyAwareRouting'](arg1);
}

export function ClearSessionToken() {
  return window['go']['pkg']['App']['ClearSessionToken']();
}

export function ClearUsageHistory() {
  return window['go']['pkg']['App']['ClearUsageHistory']();
}

export function ClearUserActivity() {
  return window['go']['pkg']['App']['ClearUserActivity']();
}

export function CloseExecSession() {
  return window['go']['pkg']['App']['CloseExecSession']();
}

export function CompleteOAuthFlow(arg1, arg2) {
  return window['go']['pkg']['App']['CompleteOAuthFlow'](arg1, arg2);
}

export function ConnectToAgent(arg1) {
  return window['go']['pkg']['App']['ConnectToAgent'](arg1);
}

export function CorrelatePodEvents(arg1, arg2, arg3) {
  return window['go']['pkg']['App']['CorrelatePodEvents'](arg1, arg2, arg3);
}

export function CreateCodeReviewReport(arg1, arg2, arg3, arg4) {
  return window['go']['pkg']['App']['CreateCodeReviewReport'](arg1, arg2, arg3, arg4);
}

export function CreateExternalBridge(arg1) {
  return window['go']['pkg']['App']['CreateExternalBridge'](arg1);
}

export function CreateIncident(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['pkg']['App']['CreateIncident'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateNotebookFolder(arg1) {
  return window['go']['pkg']['App']['CreateNotebookFolder'](arg1);
}

export function CreateRunbook(arg1, arg2) {
  return window['go']['pkg']['App']['CreateRunbook'](arg1, arg2);
}

export function CurrentMetrics() {
  return window['go']['pkg']['App']['CurrentMetrics']();
}

export function DeleteAnomalyRule(arg1) {
  return window['go']['pkg']['App']['DeleteAnomalyRule'](arg1);
}

export function DeleteCodeReviewReport(arg1, arg2) {
  return window['go']['pkg']['App']['DeleteCodeReviewReport'](arg1, arg2);
}

export function DeleteIncident(arg1) {
  return window['go']['pkg']['App']['DeleteIncident'](arg1);
}

export function DeleteNotebook(arg1) {
  return window['go']['pkg']['App']['DeleteNotebook'](arg1);
}

export function DeletePod(arg1, arg2) {
  return window['go']['pkg']['App']['DeletePod'](arg1, arg2);
}

export function DeleteResource(arg1, arg2, arg3) {
  return window['go']['pkg']['App']['DeleteResource'](arg1, arg2, arg3);
}

export function DeleteRunbook(arg1) {
  return window['go']['pkg']['App']['DeleteRunbook'](arg1);
}

export function DeleteVaultSecret(arg1) {
  return window['go']['pkg']['App']['DeleteVaultSecret'](arg1);
}

export function DeleteWorkflow(arg1) {
  return window['go']['pkg']['App']['DeleteWorkflow'](arg1);
}

export function DeployAgent(arg1) {
  return window['go']['pkg']['App']['DeployAgent'](arg1);
}

export function DescribeSecretRef(arg1) {
  return window['go']['pkg']['App']['DescribeSecretRef'](arg1);
}

export function DiagnoseAlert(arg1) {
  return window['go']['pkg']['App']['DiagnoseAlert'](arg1);
}

export function DismissSuggestion(arg1, arg2) {
  return window['go']['pkg']['App']['DismissSuggestion'](arg1, arg2);
}

export function DuplicateWorkload(arg1, arg2, arg3) {
  return window['go']['pkg']['App']['DuplicateWorkload'](arg1, arg2, arg3);
}

export function EmitLogLine(arg1) {
  return window['go']['pkg']['App']['EmitLogLine'](arg1);
}

export function EstimateCosts(arg1) {
  return window['go']['pkg']['App']['EstimateCosts'](arg1);
}

export function ExecPodShell(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['pkg']['App']['ExecPodShell'](arg1, arg2, arg3, arg4, arg5);
}

export function FindOrphanedEndpoints(arg1) {
  return window['go']['pkg']['App']['FindOrphanedEndpoints'](arg1);
}

export function GenerateTrafficSplitHTTPRoute(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['pkg']['App']['GenerateTrafficSplitHTTPRoute'](arg1, arg2, arg3, arg4, arg5);
}

export function GenerateWorkloadYAML(arg1) {
  return window['go']['pkg']['App']['GenerateWorkloadYAML'](arg1);
}

export function GetAgentEventLog() {
  return window['go']['pkg']['App']['GetAgentEventLog']();
}

export function GetAgentProfile() {
  return window['go']['pkg']['App']['GetAgentProfile']();
}

export function GetAgentTopology(arg1) {
  return window['go']['pkg']['App']['GetAgentTopology'](arg1);
}

export function GetAlerts() {
  return window['go']['pkg']['App']['GetAlerts']();
}

export function GetAnomalyJobs() {
  return window['go']['pkg']['App']['GetAnomalyJobs']();
}

export function GetAnomalyRules() {
  return window['go']['pkg']['App']['GetAnomalyRules']();
}

export function GetAnomalySettings() {
  return window['go']['pkg']['App']['GetAnomalySettings']();
}

export function GetAppMode() {
  return window['go']['pkg']['App']['GetAppMode']();
}

export function GetArgusCDApp(arg1) {
  return window['go']['pkg']['App']['GetArgusCDApp'](arg1);
}

export function GetArgusCDDiffs(arg1) {
  return window['go']['pkg']['App']['GetArgusCDDiffs'](arg1);
}

export function GetArgusCDResources(arg1) {
  return window['go']['pkg']['App']['GetArgusCDResources'](arg1);
}

export function GetArgusCDStatus() {
  return window['go']['pkg']['App']['GetArgusCDStatus']();
}

export function GetAutoSummary(arg1) {
  return window['go']['pkg']['App']['GetAutoSummary'](arg1);
}

export function GetBlastRadiusInfo() {
  return window['go']['pkg']['App']['GetBlastRadiusInfo']();
}

export function GetChatHistory(arg1) {
  return window['go']['pkg']['App']['GetChatHistory'](arg1);
}

export function GetClusterInfo() {
  return window['go']['pkg']['App']['GetClusterInfo']();
}

export function GetCodeReviewReport(arg1, arg2) {
  return window['go']['pkg']['App']['GetCodeReviewReport'](arg1, arg2);
}

export function GetCodeSuggestion(arg1, arg2) {
  return window['go']['pkg']['App']['GetCodeSuggestion'](arg1, arg2);
}

export function GetCommonPermissions(arg1) {
  return window['go']['pkg']['App']['GetCommonPermissions'](arg1);
}

export function GetCrashLogs(arg1, arg2, arg3) {
  return window['go']['pkg']['App']['GetCrashLogs'](arg1, arg2, arg3);
}

export function GetDeployArtifact(arg1, arg2) {
  return window['go']['pkg']['App']['GetDeployArtifact'](arg1, arg2);
}

export function GetDeployArtifacts() {
  return window['go']['pkg']['App']['GetDeployArtifacts']();
}

export function GetDeploymentRevisions(arg1, arg2, arg3) {
  return window['go']['pkg']['App']['GetDeploymentRevisions'](arg1, arg2, arg3);
}

export function GetFeatures() {
  return window['go']['pkg']['App']['GetFeatures']();
}

export function GetGatewayStatusByRole(arg1) {
  return window['go']['pkg']['App']['GetGatewayStatusByRole'](arg1);
}

export function GetLoadTestRecord(arg1) {
  return window['go']['pkg']['App']['GetLoadTestRecord'](arg1);
}

export function GetLoadTestStatus(arg1) {
  return window['go']['pkg']['App']['GetLoadTestStatus'](arg1);
}

export function GetMetrics() {
  return window['go']['pkg']['App']['GetMetrics']();
}

export function GetNextSuggestion(arg1) {
  return window['go']['pkg']['App']['GetNextSuggestion'](arg1);
}

export function GetNodeCapacities() {
  return window['go']['pkg']['App']['GetNodeCapacities']();
}

export function GetNodeLogs(arg1, arg2) {
  return window['go']['pkg']['App']['GetNodeLogs'](arg1, arg2);
}

export function GetNotebook(arg1) {
  return window['go']['pkg']['App']['GetNotebook'](arg1);
}

export function GetPRGuidelines(arg1) {
  return window['go']['pkg']['App']['GetPRGuidelines'](arg1);
}

export function GetPodLogs(arg1, arg2, arg3) {
  return window['go']['pkg']['App']['GetPodLogs'](arg1, arg2, arg3);
}

export function GetResourceDetail(arg1, arg2, arg3) {
  return window['go']['pkg']['App']['GetResourceDetail'](arg1, arg2, arg3);
}

export function GetResourceSuggestion(arg1) {
  return window['go']['pkg']['App']['GetResourceSuggestion'](arg1);
}

export function GetResourceYaml(arg1, arg2, arg3) {
  return window['go']['pkg']['App']['GetResourceYaml'](arg1, arg2, arg3);
}

export function GetRouteTopologyGraph(arg1) {
  return window['go']['pkg']['App']['GetRouteTopologyGraph'](arg1);
}

export function GetRunbook(arg1) {
  return window['go']['pkg']['App']['GetRunbook'](arg1);
}

export function GetSecretStoreInfo() {
  return window['go']['pkg']['App']['GetSecretStoreInfo']();
}

export function GetServicePods(arg1, arg2) {
  return window['go']['pkg']['App']['GetServicePods'](arg1, arg2);
}

export function GetSessionToken() {
  return window['go']['pkg']['App']['GetSessionToken']();
}

export function GetSettings() {
  return window['go']['pkg']['App']['GetSettings']();
}

export function GetTShirtSizes() {
  return window['go']['pkg']['App']['GetTShirtSizes']();
}

export function GetTier() {
  return window['go']['pkg']['App']['GetTier']();
}

export function GetTopology(arg1) {
  return window['go']['pkg']['App']['GetTopology'](arg1);
}

export function GetUsageSummary() {
  return window['go']['pkg']['App']['GetUsageSummary']();
}

export function GetVPARecommendations(arg1) {
  return window['go']['pkg']['App']['GetVPARecommendations'](arg1);
}

export function GetVaultStatus() {
  return window['go']['pkg']['App']['GetVaultStatus']();
}

export function GetWorkflow(arg1) {
  return window['go']['pkg']['App']['GetWorkflow'](arg1);
}

export function GetZoneDistribution(arg1, arg2) {
  return window['go']['pkg']['App']['GetZoneDistribution'](arg1, arg2);
}

export function HandleURL(arg1) {
  return window['go']['pkg']['App']['HandleURL'](arg1);
}

export function HandleWebhook(arg1, arg2) {
  return window['go']['pkg']['App']['HandleWebhook'](arg1, arg2);
}

export function ImpersonateUser(arg1, arg2) {
  return window['go']['pkg']['App']['ImpersonateUser'](arg1, arg2);
}

export function InjectDebugContainer(arg1, arg2, arg3) {
  return window['go']['pkg']['App']['InjectDebugContainer'](arg1, arg2, arg3);
}

export function InstallArgusScan() {
  return window['go']['pkg']['App']['InstallArgusScan']();
}

export function LaunchPopOutTerminal() {
  return window['go']['pkg']['App']['LaunchPopOutTerminal']();
}

export function ListAllNamespaces() {
  return window['go']['pkg']['App']['ListAllNamespaces']();
}

export function ListApplications(arg1) {
  return window['go']['pkg']['App']['ListApplications'](arg1);
}

export function ListArgusCDApps(arg1) {
  return window['go']['pkg']['App']['ListArgusCDApps'](arg1);
}

export function ListArgusCDProjects() {
  return window['go']['pkg']['App']['ListArgusCDProjects']();
}

export function ListBrokerKinds() {
  return window['go']['pkg']['App']['ListBrokerKinds']();
}

export function ListCodeReviewReports(arg1) {
  return window['go']['pkg']['App']['ListCodeReviewReports'](arg1);
}

export function ListContexts() {
  return window['go']['pkg']['App']['ListContexts']();
}

export function ListEncryptedSecretSources(arg1) {
  return window['go']['pkg']['App']['ListEncryptedSecretSources'](arg1);
}

export function ListEndpointSlices(arg1) {
  return window['go']['pkg']['App']['ListEndpointSlices'](arg1);
}

export function ListExternalBridges(arg1) {
  return window['go']['pkg']['App']['ListExternalBridges'](arg1);
}

export function ListGatewayClasses() {
  return window['go']['pkg']['App']['ListGatewayClasses']();
}

export function ListGateways(arg1) {
  return window['go']['pkg']['App']['ListGateways'](arg1);
}

export function ListGitHubBranches() {
  return window['go']['pkg']['App']['ListGitHubBranches']();
}

export function ListGitHubPullRequests() {
  return window['go']['pkg']['App']['ListGitHubPullRequests']();
}

export function ListHTTPRoutes(arg1) {
  return window['go']['pkg']['App']['ListHTTPRoutes'](arg1);
}

export function ListIncidents() {
  return window['go']['pkg']['App']['ListIncidents']();
}

export function ListLoadTestPresets() {
  return window['go']['pkg']['App']['ListLoadTestPresets']();
}

export function ListNamespaces() {
  return window['go']['pkg']['App']['ListNamespaces']();
}

export function ListNotebooks() {
  return window['go']['pkg']['App']['ListNotebooks']();
}

export function ListOAuthProviders() {
  return window['go']['pkg']['App']['ListOAuthProviders']();
}

export function ListRegistryTags(arg1) {
  return window['go']['pkg']['App']['ListRegistryTags'](arg1);
}

export function ListResources(arg1, arg2) {
  return window['go']['pkg']['App']['ListResources'](arg1, arg2);
}

export function ListRunbooks() {
  return window['go']['pkg']['App']['ListRunbooks']();
}

export function ListServiceSelectors(arg1) {
  return window['go']['pkg']['App']['ListServiceSelectors'](arg1);
}

export function ListSpotChecks() {
  return window['go']['pkg']['App']['ListSpotChecks']();
}

export function ListVaultSecrets() {
  return window['go']['pkg']['App']['ListVaultSecrets']();
}

export function ListVulnerabilities() {
  return window['go']['pkg']['App']['ListVulnerabilities']();
}

export function ListWorkflows() {
  return window['go']['pkg']['App']['ListWorkflows']();
}

export function LoginSaaS(arg1) {
  return window['go']['pkg']['App']['LoginSaaS'](arg1);
}

export function MarkAlertIgnored(arg1) {
  return window['go']['pkg']['App']['MarkAlertIgnored'](arg1);
}

export function MoveNotebook(arg1, arg2) {
  return window['go']['pkg']['App']['MoveNotebook'](arg1, arg2);
}

export function MuteSuggestion(arg1) {
  return window['go']['pkg']['App']['MuteSuggestion'](arg1);
}

export function PingExternalEndpoint(arg1, arg2) {
  return window['go']['pkg']['App']['PingExternalEndpoint'](arg1, arg2);
}

export function PollOAuthFlow(arg1) {
  return window['go']['pkg']['App']['PollOAuthFlow'](arg1);
}

export function ProfileWaste(arg1) {
  return window['go']['pkg']['App']['ProfileWaste'](arg1);
}

export function QueryLogs(arg1, arg2, arg3) {
  return window['go']['pkg']['App']['QueryLogs'](arg1, arg2, arg3);
}

export function QueryPromQL(arg1, arg2, arg3) {
  return window['go']['pkg']['App']['QueryPromQL'](arg1, arg2, arg3);
}

export function QueryTimeSeriesMetrics(arg1, arg2) {
  return window['go']['pkg']['App']['QueryTimeSeriesMetrics'](arg1, arg2);
}

export function RecordView(arg1, arg2, arg3) {
  return window['go']['pkg']['App']['RecordView'](arg1, arg2, arg3);
}

export function RefreshArgusCDApp(arg1, arg2) {
  return window['go']['pkg']['App']['RefreshArgusCDApp'](arg1, arg2);
}

export function ResizeExec(arg1, arg2) {
  return window['go']['pkg']['App']['ResizeExec'](arg1, arg2);
}

export function ResizeTerminal(arg1, arg2) {
  return window['go']['pkg']['App']['ResizeTerminal'](arg1, arg2);
}

export function ResolveSecretRef(arg1) {
  return window['go']['pkg']['App']['ResolveSecretRef'](arg1);
}

export function RestartDeployment(arg1, arg2) {
  return window['go']['pkg']['App']['RestartDeployment'](arg1, arg2);
}

export function RollbackArgusCDApp(arg1, arg2) {
  return window['go']['pkg']['App']['RollbackArgusCDApp'](arg1, arg2);
}

export function RunArgusScan() {
  return window['go']['pkg']['App']['RunArgusScan']();
}

export function RunCodeSandbox(arg1, arg2) {
  return window['go']['pkg']['App']['RunCodeSandbox'](arg1, arg2);
}

export function RunCronJob(arg1, arg2) {
  return window['go']['pkg']['App']['RunCronJob'](arg1, arg2);
}

export function RunEnvProbes() {
  return window['go']['pkg']['App']['RunEnvProbes']();
}

export function RunSpotCheck(arg1) {
  return window['go']['pkg']['App']['RunSpotCheck'](arg1);
}

export function RunSpotChecks() {
  return window['go']['pkg']['App']['RunSpotChecks']();
}

export function SaveAnomalyRule(arg1) {
  return window['go']['pkg']['App']['SaveAnomalyRule'](arg1);
}

export function SaveAnomalySettings(arg1) {
  return window['go']['pkg']['App']['SaveAnomalySettings'](arg1);
}

export function SaveNotebook(arg1, arg2) {
  return window['go']['pkg']['App']['SaveNotebook'](arg1, arg2);
}

export function SavePRGuidelines(arg1, arg2) {
  return window['go']['pkg']['App']['SavePRGuidelines'](arg1, arg2);
}

export function SaveRunbook(arg1, arg2) {
  return window['go']['pkg']['App']['SaveRunbook'](arg1, arg2);
}

export function SaveWorkflow(arg1) {
  return window['go']['pkg']['App']['SaveWorkflow'](arg1);
}

export function ScaleDeployment(arg1, arg2, arg3) {
  return window['go']['pkg']['App']['ScaleDeployment'](arg1, arg2, arg3);
}

export function ScanAllImages(arg1) {
  return window['go']['pkg']['App']['ScanAllImages'](arg1);
}

export function ScanImage(arg1, arg2) {
  return window['go']['pkg']['App']['ScanImage'](arg1, arg2);
}

export function SendChatMessage(arg1, arg2) {
  return window['go']['pkg']['App']['SendChatMessage'](arg1, arg2);
}

export function SendExecInput(arg1) {
  return window['go']['pkg']['App']['SendExecInput'](arg1);
}

export function SendTerminalInput(arg1) {
  return window['go']['pkg']['App']['SendTerminalInput'](arg1);
}

export function ServeHTTP(arg1, arg2) {
  return window['go']['pkg']['App']['ServeHTTP'](arg1, arg2);
}

export function SetAgentProfile(arg1) {
  return window['go']['pkg']['App']['SetAgentProfile'](arg1);
}

export function SetPaused(arg1) {
  return window['go']['pkg']['App']['SetPaused'](arg1);
}

export function SetSessionToken(arg1) {
  return window['go']['pkg']['App']['SetSessionToken'](arg1);
}

export function SetVaultSecret(arg1, arg2, arg3) {
  return window['go']['pkg']['App']['SetVaultSecret'](arg1, arg2, arg3);
}

export function SetupAuth(arg1, arg2) {
  return window['go']['pkg']['App']['SetupAuth'](arg1, arg2);
}

export function SilenceAlert(arg1, arg2, arg3) {
  return window['go']['pkg']['App']['SilenceAlert'](arg1, arg2, arg3);
}

export function StartEnvProbeLoop(arg1) {
  return window['go']['pkg']['App']['StartEnvProbeLoop'](arg1);
}

export function StartEventLoop(arg1) {
  return window['go']['pkg']['App']['StartEventLoop'](arg1);
}

export function StartHTTPServer(arg1) {
  return window['go']['pkg']['App']['StartHTTPServer'](arg1);
}

export function StartLoadTest(arg1) {
  return window['go']['pkg']['App']['StartLoadTest'](arg1);
}

export function StartOAuthFlow(arg1) {
  return window['go']['pkg']['App']['StartOAuthFlow'](arg1);
}

export function StartTerminal(arg1, arg2) {
  return window['go']['pkg']['App']['StartTerminal'](arg1, arg2);
}

export function StreamPodLogsFollow(arg1, arg2, arg3, arg4) {
  return window['go']['pkg']['App']['StreamPodLogsFollow'](arg1, arg2, arg3, arg4);
}

export function SwitchContext(arg1) {
  return window['go']['pkg']['App']['SwitchContext'](arg1);
}

export function SyncApplication(arg1, arg2) {
  return window['go']['pkg']['App']['SyncApplication'](arg1, arg2);
}

export function SyncArgusCDApp(arg1, arg2) {
  return window['go']['pkg']['App']['SyncArgusCDApp'](arg1, arg2);
}

export function TestArgusCDConnection() {
  return window['go']['pkg']['App']['TestArgusCDConnection']();
}

export function TestS3Connection() {
  return window['go']['pkg']['App']['TestS3Connection']();
}

export function TestSecretsTool(arg1) {
  return window['go']['pkg']['App']['TestSecretsTool'](arg1);
}

export function TestVaultProvider(arg1) {
  return window['go']['pkg']['App']['TestVaultProvider'](arg1);
}

export function ToggleAnomalyRule(arg1) {
  return window['go']['pkg']['App']['ToggleAnomalyRule'](arg1);
}

export function TranslateIngressToGateway(arg1) {
  return window['go']['pkg']['App']['TranslateIngressToGateway'](arg1);
}

export function UndeployAgent(arg1) {
  return window['go']['pkg']['App']['UndeployAgent'](arg1);
}

export function UpdateBillingRates(arg1, arg2, arg3) {
  return window['go']['pkg']['App']['UpdateBillingRates'](arg1, arg2, arg3);
}

export function UpdateIncident(arg1, arg2, arg3) {
  return window['go']['pkg']['App']['UpdateIncident'](arg1, arg2, arg3);
}

export function UpdateSettings(arg1) {
  return window['go']['pkg']['App']['UpdateSettings'](arg1);
}

export function ValidateEnvFile(arg1, arg2, arg3) {
  return window['go']['pkg']['App']['ValidateEnvFile'](arg1, arg2, arg3);
}
