apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "kubewatcher-backend.fullname" . }}-data
  labels:
    {{- include "kubewatcher-backend.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size | default "10Gi" }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
