apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubewatcher-backend.fullname" . }}
  labels:
    {{- include "kubewatcher-backend.labels" . | nindent 4 }}
  {{- if .Values.service.annotations }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port | default 8080 }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "kubewatcher-backend.selectorLabels" . | nindent 4 }}
