// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {setup} from '../models';
import {agentconn} from '../models';
import {incidents} from '../models';
import {runbooks} from '../models';
import {context} from '../models';
import {alerts} from '../models';
import {ai} from '../models';
import {anomaly} from '../models';
import {k8s} from '../models';
import {features} from '../models';
import {config} from '../models';
import {notebooks} from '../models';
import {vulnscan} from '../models';
import {popeye} from '../models';
import {http} from '../models';

export function CheckToolStatus():Promise<Array<setup.ToolStatus>>;

export function ConnectToAgent(arg1:string):Promise<Array<agentconn.Anomaly>>;

export function CreateIncident(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<incidents.Incident>;

export function CreateNotebookFolder(arg1:string):Promise<void>;

export function CreateRunbook(arg1:string,arg2:string):Promise<runbooks.Runbook>;

export function DeleteIncident(arg1:string):Promise<void>;

export function DeleteNotebook(arg1:string):Promise<void>;

export function DeletePod(arg1:string,arg2:string):Promise<void>;

export function DeleteRunbook(arg1:string):Promise<void>;

export function DeployAgent(arg1:string):Promise<setup.SetupResult>;

export function DiagnoseAlert(arg1:string):Promise<context.Bundle>;

export function EmitLogLine(arg1:alerts.LogLine):Promise<void>;

export function GetAgentEventLog():Promise<Array<ai.AgentEvent>>;

export function GetAgentTopology(arg1:string):Promise<agentconn.TopologyGraph>;

export function GetAlerts():Promise<Array<alerts.Alert>>;

export function GetAnomalyJobs():Promise<Array<anomaly.Job>>;

export function GetAppMode():Promise<string>;

export function GetAutoSummary(arg1:string):Promise<ai.AutoSummary>;

export function GetChatHistory(arg1:string):Promise<Array<ai.ChatEntry>>;

export function GetClusterInfo():Promise<k8s.ClusterInfo>;

export function GetCodeSuggestion(arg1:string,arg2:string):Promise<string>;

export function GetFeatures():Promise<Record<features.Feature, boolean>>;

export function GetMetrics():Promise<alerts.ClusterMetrics>;

export function GetNotebook(arg1:string):Promise<string>;

export function GetPodLogs(arg1:string,arg2:string,arg3:number):Promise<Array<alerts.LogLine>>;

export function GetResourceDetail(arg1:string,arg2:string,arg3:string):Promise<k8s.ResourceDetailResult>;

export function GetRunbook(arg1:string):Promise<string>;

export function GetTier():Promise<config.Tier>;

export function GetTopology(arg1:string):Promise<k8s.TopologyResult>;

export function HandleURL(arg1:string):Promise<void>;

export function InstallPopeye():Promise<setup.SetupResult>;

export function ListAllNamespaces():Promise<Array<string>>;

export function ListApplications(arg1:string):Promise<Array<k8s.Application>>;

export function ListContexts():Promise<Array<k8s.ContextInfo>>;

export function ListIncidents():Promise<Array<incidents.Incident>>;

export function ListNotebooks():Promise<Array<notebooks.FileEntry>>;

export function ListResources(arg1:string,arg2:string):Promise<k8s.ResourceListResult>;

export function ListRunbooks():Promise<Array<runbooks.Runbook>>;

export function ListVulnerabilities():Promise<Array<vulnscan.ScannedImage>>;

export function LoginSaaS(arg1:string):Promise<string>;

export function MoveNotebook(arg1:string,arg2:string):Promise<void>;

export function QueryLogs(arg1:string,arg2:string,arg3:number):Promise<k8s.LogQueryResult>;

export function QueryTimeSeriesMetrics(arg1:string,arg2:string):Promise<Array<number>>;

export function ResizeTerminal(arg1:number,arg2:number):Promise<void>;

export function RunCodeSandbox(arg1:string,arg2:string):Promise<string>;

export function RunPopeye():Promise<popeye.Report>;

export function SaveNotebook(arg1:string,arg2:string):Promise<void>;

export function SaveRunbook(arg1:string,arg2:string):Promise<void>;

export function ScanAllImages(arg1:string):Promise<Array<vulnscan.ScannedImage>>;

export function ScanImage(arg1:string,arg2:string):Promise<string>;

export function SendChatMessage(arg1:string,arg2:string):Promise<string>;

export function SendTerminalInput(arg1:string):Promise<void>;

export function ServeHTTP(arg1:http.ResponseWriter,arg2:http.Request):Promise<void>;

export function StartEventLoop(arg1:context.Context):Promise<void>;

export function StartHTTPServer(arg1:number):Promise<void>;

export function StartTerminal(arg1:number,arg2:number):Promise<void>;

export function SwitchContext(arg1:string):Promise<void>;

export function SyncApplication(arg1:string,arg2:string):Promise<void>;

export function TestS3Connection():Promise<void>;

export function UndeployAgent(arg1:string):Promise<setup.SetupResult>;

export function UpdateIncident(arg1:string,arg2:string,arg3:string):Promise<incidents.Incident>;
