// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectToAgent(arg1) {
  return window['go']['pkg']['App']['ConnectToAgent'](arg1);
}

export function DiagnoseAlert(arg1) {
  return window['go']['pkg']['App']['DiagnoseAlert'](arg1);
}

export function EmitLogLine(arg1) {
  return window['go']['pkg']['App']['EmitLogLine'](arg1);
}

export function GetAgentEventLog() {
  return window['go']['pkg']['App']['GetAgentEventLog']();
}

export function GetAlerts() {
  return window['go']['pkg']['App']['GetAlerts']();
}

export function GetAnomalyJobs() {
  return window['go']['pkg']['App']['GetAnomalyJobs']();
}

export function GetAutoSummary(arg1) {
  return window['go']['pkg']['App']['GetAutoSummary'](arg1);
}

export function GetChatHistory(arg1) {
  return window['go']['pkg']['App']['GetChatHistory'](arg1);
}

export function GetClusterInfo() {
  return window['go']['pkg']['App']['GetClusterInfo']();
}

export function GetFeatures() {
  return window['go']['pkg']['App']['GetFeatures']();
}

export function GetMetrics() {
  return window['go']['pkg']['App']['GetMetrics']();
}

export function GetPodLogs(arg1, arg2, arg3) {
  return window['go']['pkg']['App']['GetPodLogs'](arg1, arg2, arg3);
}

export function GetResourceDetail(arg1, arg2, arg3) {
  return window['go']['pkg']['App']['GetResourceDetail'](arg1, arg2, arg3);
}

export function GetTier() {
  return window['go']['pkg']['App']['GetTier']();
}

export function ListAllNamespaces() {
  return window['go']['pkg']['App']['ListAllNamespaces']();
}

export function ListResources(arg1, arg2) {
  return window['go']['pkg']['App']['ListResources'](arg1, arg2);
}

export function LoginSaaS(arg1) {
  return window['go']['pkg']['App']['LoginSaaS'](arg1);
}

export function ResizeTerminal(arg1, arg2) {
  return window['go']['pkg']['App']['ResizeTerminal'](arg1, arg2);
}

export function RunPopeye() {
  return window['go']['pkg']['App']['RunPopeye']();
}

export function SendChatMessage(arg1, arg2) {
  return window['go']['pkg']['App']['SendChatMessage'](arg1, arg2);
}

export function SendTerminalInput(arg1) {
  return window['go']['pkg']['App']['SendTerminalInput'](arg1);
}

export function StartEventLoop(arg1) {
  return window['go']['pkg']['App']['StartEventLoop'](arg1);
}

export function StartTerminal(arg1, arg2) {
  return window['go']['pkg']['App']['StartTerminal'](arg1, arg2);
}
