// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {pkg} from '../models';
import {context} from '../models';
import {alerts} from '../models';
import {ai} from '../models';
import {anomaly} from '../models';
import {k8s} from '../models';
import {features} from '../models';
import {config} from '../models';
import {popeye} from '../models';

export function ConnectToAgent(arg1:string):Promise<Array<pkg.AgentAnomaly>>;

export function DiagnoseAlert(arg1:string):Promise<context.Bundle>;

export function EmitLogLine(arg1:alerts.LogLine):Promise<void>;

export function GetAgentEventLog():Promise<Array<ai.AgentEvent>>;

export function GetAlerts():Promise<Array<alerts.Alert>>;

export function GetAnomalyJobs():Promise<Array<anomaly.Job>>;

export function GetAutoSummary(arg1:string):Promise<ai.AutoSummary>;

export function GetChatHistory(arg1:string):Promise<Array<ai.ChatEntry>>;

export function GetClusterInfo():Promise<k8s.ClusterInfo>;

export function GetFeatures():Promise<Record<features.Feature, boolean>>;

export function GetMetrics():Promise<alerts.ClusterMetrics>;

export function GetPodLogs(arg1:string,arg2:string,arg3:number):Promise<Array<alerts.LogLine>>;

export function GetResourceDetail(arg1:string,arg2:string,arg3:string):Promise<k8s.ResourceDetailResult>;

export function GetTier():Promise<config.Tier>;

export function ListAllNamespaces():Promise<Array<string>>;

export function ListResources(arg1:string,arg2:string):Promise<k8s.ResourceListResult>;

export function LoginSaaS(arg1:string):Promise<string>;

export function ResizeTerminal(arg1:number,arg2:number):Promise<void>;

export function RunPopeye():Promise<popeye.Report>;

export function SendChatMessage(arg1:string,arg2:string):Promise<string>;

export function SendTerminalInput(arg1:string):Promise<void>;

export function StartEventLoop(arg1:context.Context):Promise<void>;

export function StartTerminal(arg1:number,arg2:number):Promise<void>;
