// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckToolStatus() {
  return window['go']['pkg']['App']['CheckToolStatus']();
}

export function ConnectToAgent(arg1) {
  return window['go']['pkg']['App']['ConnectToAgent'](arg1);
}

export function CreateIncident(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['pkg']['App']['CreateIncident'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateNotebookFolder(arg1) {
  return window['go']['pkg']['App']['CreateNotebookFolder'](arg1);
}

export function CreateRunbook(arg1, arg2) {
  return window['go']['pkg']['App']['CreateRunbook'](arg1, arg2);
}

export function DeleteIncident(arg1) {
  return window['go']['pkg']['App']['DeleteIncident'](arg1);
}

export function DeleteNotebook(arg1) {
  return window['go']['pkg']['App']['DeleteNotebook'](arg1);
}

export function DeletePod(arg1, arg2) {
  return window['go']['pkg']['App']['DeletePod'](arg1, arg2);
}

export function DeleteRunbook(arg1) {
  return window['go']['pkg']['App']['DeleteRunbook'](arg1);
}

export function DeployAgent(arg1) {
  return window['go']['pkg']['App']['DeployAgent'](arg1);
}

export function DiagnoseAlert(arg1) {
  return window['go']['pkg']['App']['DiagnoseAlert'](arg1);
}

export function EmitLogLine(arg1) {
  return window['go']['pkg']['App']['EmitLogLine'](arg1);
}

export function GetAgentEventLog() {
  return window['go']['pkg']['App']['GetAgentEventLog']();
}

export function GetAgentTopology(arg1) {
  return window['go']['pkg']['App']['GetAgentTopology'](arg1);
}

export function GetAlerts() {
  return window['go']['pkg']['App']['GetAlerts']();
}

export function GetAnomalyJobs() {
  return window['go']['pkg']['App']['GetAnomalyJobs']();
}

export function GetAppMode() {
  return window['go']['pkg']['App']['GetAppMode']();
}

export function GetAutoSummary(arg1) {
  return window['go']['pkg']['App']['GetAutoSummary'](arg1);
}

export function GetChatHistory(arg1) {
  return window['go']['pkg']['App']['GetChatHistory'](arg1);
}

export function GetClusterInfo() {
  return window['go']['pkg']['App']['GetClusterInfo']();
}

export function GetCodeSuggestion(arg1, arg2) {
  return window['go']['pkg']['App']['GetCodeSuggestion'](arg1, arg2);
}

export function GetFeatures() {
  return window['go']['pkg']['App']['GetFeatures']();
}

export function GetMetrics() {
  return window['go']['pkg']['App']['GetMetrics']();
}

export function GetNotebook(arg1) {
  return window['go']['pkg']['App']['GetNotebook'](arg1);
}

export function GetPodLogs(arg1, arg2, arg3) {
  return window['go']['pkg']['App']['GetPodLogs'](arg1, arg2, arg3);
}

export function GetResourceDetail(arg1, arg2, arg3) {
  return window['go']['pkg']['App']['GetResourceDetail'](arg1, arg2, arg3);
}

export function GetRunbook(arg1) {
  return window['go']['pkg']['App']['GetRunbook'](arg1);
}

export function GetTier() {
  return window['go']['pkg']['App']['GetTier']();
}

export function GetTopology(arg1) {
  return window['go']['pkg']['App']['GetTopology'](arg1);
}

export function HandleURL(arg1) {
  return window['go']['pkg']['App']['HandleURL'](arg1);
}

export function InstallPopeye() {
  return window['go']['pkg']['App']['InstallPopeye']();
}

export function ListAllNamespaces() {
  return window['go']['pkg']['App']['ListAllNamespaces']();
}

export function ListApplications(arg1) {
  return window['go']['pkg']['App']['ListApplications'](arg1);
}

export function ListContexts() {
  return window['go']['pkg']['App']['ListContexts']();
}

export function ListIncidents() {
  return window['go']['pkg']['App']['ListIncidents']();
}

export function ListNotebooks() {
  return window['go']['pkg']['App']['ListNotebooks']();
}

export function ListResources(arg1, arg2) {
  return window['go']['pkg']['App']['ListResources'](arg1, arg2);
}

export function ListRunbooks() {
  return window['go']['pkg']['App']['ListRunbooks']();
}

export function ListVulnerabilities() {
  return window['go']['pkg']['App']['ListVulnerabilities']();
}

export function LoginSaaS(arg1) {
  return window['go']['pkg']['App']['LoginSaaS'](arg1);
}

export function MoveNotebook(arg1, arg2) {
  return window['go']['pkg']['App']['MoveNotebook'](arg1, arg2);
}

export function QueryLogs(arg1, arg2, arg3) {
  return window['go']['pkg']['App']['QueryLogs'](arg1, arg2, arg3);
}

export function QueryTimeSeriesMetrics(arg1, arg2) {
  return window['go']['pkg']['App']['QueryTimeSeriesMetrics'](arg1, arg2);
}

export function ResizeTerminal(arg1, arg2) {
  return window['go']['pkg']['App']['ResizeTerminal'](arg1, arg2);
}

export function RunCodeSandbox(arg1, arg2) {
  return window['go']['pkg']['App']['RunCodeSandbox'](arg1, arg2);
}

export function RunPopeye() {
  return window['go']['pkg']['App']['RunPopeye']();
}

export function SaveNotebook(arg1, arg2) {
  return window['go']['pkg']['App']['SaveNotebook'](arg1, arg2);
}

export function SaveRunbook(arg1, arg2) {
  return window['go']['pkg']['App']['SaveRunbook'](arg1, arg2);
}

export function ScanAllImages(arg1) {
  return window['go']['pkg']['App']['ScanAllImages'](arg1);
}

export function ScanImage(arg1, arg2) {
  return window['go']['pkg']['App']['ScanImage'](arg1, arg2);
}

export function SendChatMessage(arg1, arg2) {
  return window['go']['pkg']['App']['SendChatMessage'](arg1, arg2);
}

export function SendTerminalInput(arg1) {
  return window['go']['pkg']['App']['SendTerminalInput'](arg1);
}

export function ServeHTTP(arg1, arg2) {
  return window['go']['pkg']['App']['ServeHTTP'](arg1, arg2);
}

export function StartEventLoop(arg1) {
  return window['go']['pkg']['App']['StartEventLoop'](arg1);
}

export function StartHTTPServer(arg1) {
  return window['go']['pkg']['App']['StartHTTPServer'](arg1);
}

export function StartTerminal(arg1, arg2) {
  return window['go']['pkg']['App']['StartTerminal'](arg1, arg2);
}

export function SwitchContext(arg1) {
  return window['go']['pkg']['App']['SwitchContext'](arg1);
}

export function SyncApplication(arg1, arg2) {
  return window['go']['pkg']['App']['SyncApplication'](arg1, arg2);
}

export function TestS3Connection() {
  return window['go']['pkg']['App']['TestS3Connection']();
}

export function UndeployAgent(arg1) {
  return window['go']['pkg']['App']['UndeployAgent'](arg1);
}

export function UpdateIncident(arg1, arg2, arg3) {
  return window['go']['pkg']['App']['UpdateIncident'](arg1, arg2, arg3);
}
